translate zh_hans strings:
    old "Self-voicing disabled."
    new "自动语音已禁用。"
    old "Clipboard voicing enabled. "
    new "剪贴板语音已启用。"
    old "Self-voicing enabled. "
    new "自动语音已启用。"
    old "bar"
    new "滚动条"
    old "selected"
    new "已选择"
    old "viewport"
    new "视口"
    old "horizontal scroll"
    new "水平滚动"
    old "vertical scroll"
    new "垂直滚动"
    old "activate"
    new "激活"
    old "deactivate"
    new "停用"
    old "increase"
    new "增加"
    old "decrease"
    new "减少"
    old "Accessibility Menu. Use up and down arrows to navigate, and enter to activate buttons and bars."
    new "辅助功能菜单。使用上下箭头导航，按回车键激活按钮和滚动条。"
    old "Font Override"
    new "字体覆盖"
    old "Default"
    new "默认"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "文本大小缩放"
    old "Reset"
    new "重置"
    old "Line Spacing Scaling"
    new "行间距缩放"
    old "High Contrast Text"
    new "高对比度文本"
    old "Enable"
    new "启用"
    old "Disable"
    new "禁用"
    old "Self-Voicing"
    new "自动语音"
    old "Self-voicing support is limited when using a touch screen."
    new "在使用触摸屏时，自动语音功能会受限。"
    old "Off"
    new "关"
    old "Text-to-speech"
    new "文本转语音"
    old "Clipboard"
    new "剪贴板"
    old "Debug"
    new "调试"
    old "Self-Voicing Volume Drop"
    new "自动语音音量降低"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "此页面的选项，可为玩家提供更舒适的游玩体验。这些选项没有通用性，不适用于所有游戏，某些错误的选择甚至会导致游戏崩溃。当然，这不是游戏本身或游戏引擎的问题。在更改字体时，尽量保持文本大小与原始大小相同，以获得最佳体验。"
    old "Monday"
    new "星期一"
    old "Tuesday"
    new "星期二"
    old "Wednesday"
    new "星期三"
    old "Thursday"
    new "星期四"
    old "Friday"
    new "星期五"
    old "Saturday"
    new "星期六"
    old "Sunday"
    new "星期日"
    old "Mon"
    new "周一"
    old "Tue"
    new "周二"
    old "Wed"
    new "周三"
    old "Thu"
    new "周四"
    old "Fri"
    new "周五"
    old "Sat"
    new "周六"
    old "Sun"
    new "周日"
    old "January"
    new "January"
    old "February"
    new "February"
    old "March"
    new "March"
    old "April"
    new "April"
    old "May"
    new "May"
    old "June"
    new "June"
    old "July"
    new "July"
    old "August"
    new "August"
    old "September"
    new "September"
    old "October"
    new "October"
    old "November"
    new "November"
    old "December"
    new "December"
    old "Jan"
    new "一月"
    old "Feb"
    new "二月"
    old "Mar"
    new "三月"
    old "Apr"
    new "四月"
    old "Jun"
    new "六月"
    old "Jul"
    new "七月"
    old "Aug"
    new "八月"
    old "Sep"
    new "九月"
    old "Oct"
    new "十月"
    old "Nov"
    new "十一月"
    old "Dec"
    new "十二月"
    old "%b %d, %H:%M"
    new "%b %d, %H:%M"
    old "Save slot %s: [text]"
    new "保存存档 %s: [text]"
    old "Load slot %s: [text]"
    new "加载存档 %s: [text]"
    old "Delete slot [text]"
    new "删除存档[text]"
    old "File page auto"
    new "自动保存的存档"
    old "File page quick"
    new "快速保存的存档"
    old "File page [text]"
    new "存档页[text]"
    old "Next file page."
    new "下一页。"
    old "Previous file page."
    new "上一页。"
    old "Quick save complete."
    new "快速保存已完成。"
    old "Quick save."
    new "快速保存。"
    old "Quick load."
    new "快速加载。"
    old "Language [text]"
    new "语言[text]"
    old "Open [text] directory."
    new "打开[text]目录。"
    old "The interactive director is not enabled here."
    new "导演交互功能未启用。"
    old "⬆"
    new "⬆"
    old "⬇"
    new "⬇"
    old "Done"
    new "完成"
    old "(statement)"
    new "(statement)"
    old "(tag)"
    new "(tag)"
    old "(attributes)"
    new "(attributes)"
    old "(transform)"
    new "(transform)"
    old "(transition)"
    new "(transition)"
    old "(channel)"
    new "(channel)"
    old "(filename)"
    new "(filename)"
    old "Change"
    new "更改"
    old "Add"
    new "添加"
    old "Cancel"
    new "取消"
    old "Remove"
    new "移除"
    old "Statement:"
    new "语句:"
    old "Tag:"
    new "标签:"
    old "Attributes:"
    new "属性:"
    old "Click to toggle attribute, right click to toggle negative attribute."
    new "点击切换属性，右键点击切换为相反属性。"
    old "Transforms:"
    new "变换:"
    old "Click to set transform, right click to add to transform list."
    new "点击设置变换，右键点击添加到变换列表。"
    old "Customize director.transforms to add more transforms."
    new "自定义director.transforms以添加更多变换。"
    old "Behind:"
    new "背后:"
    old "Click to set, right click to add to behind list."
    new "点击设置，右键点击添加到背后列表。"
    old "Transition:"
    new "过渡:"
    old "Click to set."
    new "点击设置。"
    old "Customize director.transitions to add more transitions."
    new "自定义director.transitions以添加更多过渡。"
    old "Channel:"
    new "通道:"
    old "Customize director.audio_channels to add more channels."
    new "自定义director.audio_channels以添加更多通道。"
    old "Audio Filename:"
    new "音频文件名:"
    old "Are you sure?"
    new "你确定吗？"
    old "Are you sure you want to delete this save?"
    new "你确定要删除这个存档吗？"
    old "Are you sure you want to overwrite your save?"
    new "你确定要覆盖你的存档吗？"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "加载存档将丢失当前游戏进度。\n你确定要继续吗？"
    old "Are you sure you want to quit?"
    new "你确定要退出吗？"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "你确定要返回主菜单吗？\n未存档的进度会丢失。"
    old "Are you sure you want to continue where you left off?"
    new "你确定要继续游戏吗？"
    old "Are you sure you want to end the replay?"
    new "你确定要结束回放吗？"
    old "Are you sure you want to begin skipping?"
    new "你确定要开启快进功能吗？"
    old "Are you sure you want to skip to the next choice?"
    new "你确定要快进到下一个选项吗？"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "你确定要跳过未读文本，直接跳转到下一个选项吗？"
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new "此存档来自其他设备。恶意存档可能会对你的设备产生不好的影响。你信任这个存档的创建者吗？"
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new "你信任创建该存档的原设备吗？如果信任，请选择“是”。"
    old "Failed to save screenshot as %s."
    new "无法将截图保存为 %s。"
    old "Saved screenshot as %s."
    new "已将截图保存为 %s。"
    old "Skip Mode"
    new "快进模式"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "此程序包含许多开源代码以及其他许可，包括MIT许可证和GNU较宽松通用公共许可证。完整的软件列表，包括完整源代码链接，可以在{a=https://www.renpy.org/l/license}这里{/a}找到。"
    old "display"
    new "显示"
    old "transitions"
    new "过渡"
    old "skip transitions"
    new "跳过过渡"
    old "video sprites"
    new "视频精灵"
    old "show empty window"
    new "显示空窗口"
    old "text speed"
    new "文本速度"
    old "joystick"
    new "操纵杆"
    old "joystick..."
    new "操纵杆……"
    old "skip"
    new "跳过"
    old "skip unseen [text]"
    new "跳过未读文本[text]"
    old "skip unseen text"
    new "跳过未读文本"
    old "begin skipping"
    new "开始跳过"
    old "after choices"
    new "完成选项之后"
    old "skip after choices"
    new "完成选项之后继续快进"
    old "auto-forward time"
    new "自动加载时间"
    old "auto-forward"
    new "自动加载"
    old "Auto forward"
    new "自动加载"
    old "auto-forward after click"
    new "点击后自动加载"
    old "automatic move"
    new "自行移动"
    old "wait for voice"
    new "等待语音"
    old "voice sustain"
    new "语音持续"
    old "self voicing"
    new "自动语音"
    old "self voicing enable"
    new "启用自动语音"
    old "self voicing disable"
    new "禁用自动语音"
    old "self voicing volume drop"
    new "自动语音音量降低"
    old "clipboard voicing"
    new "剪贴板语音"
    old "clipboard voicing enable"
    new "启用剪贴板语音"
    old "clipboard voicing disable"
    new "禁用剪贴板语音"
    old "debug voicing"
    new "调试语音"
    old "debug voicing enable"
    new "启用调试语音"
    old "debug voicing disable"
    new "禁用调试语音"
    old "emphasize audio"
    new "强调音频"
    old "rollback side"
    new "返回区域"
    old "gl powersave"
    new "GL节能"
    old "gl framerate"
    new "GL帧率"
    old "gl tearing"
    new "GL撕裂"
    old "font transform"
    new "字体变换"
    old "font size"
    new "字体大小"
    old "font line spacing"
    new "字体行间距"
    old "system cursor"
    new "系统光标"
    old "renderer menu"
    new "渲染器菜单"
    old "accessibility menu"
    new "辅助功能菜单"
    old "audio when minimized"
    new "最小化时音频"
    old "audio when unfocused"
    new "未聚焦时音频"
    old "web cache preload"
    new "网页缓存预加载"
    old "voice after game menu"
    new "打开游戏菜单后语音"
    old "restore window position"
    new "恢复窗口位置"
    old "main volume"
    new "主音量"
    old "music volume"
    new "音乐音量"
    old "sound volume"
    new "音效音量"
    old "voice volume"
    new "语音音量"
    old "mute main"
    new "静音主音量"
    old "mute music"
    new "静音音乐"
    old "mute sound"
    new "静音音效"
    old "mute voice"
    new "静音语音"
    old "mute all"
    new "静音全部"
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new "剪贴板语音已启用。按 'shift+C' 禁用。"
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new "自动语音会说\"[renpy.display.tts.last]\"。按 'alt+shift+V' 禁用此功能。"
    old "Self-voicing enabled. Press 'v' to disable."
    new "自动语音已启用。按 'v' 禁用。"
    old "Speech Bubble Editor"
    new "对话泡编辑器"
    old "(hide)"
    new "(hide)"
    old "(clear retained bubbles)"
    new "(clear retained bubbles)"
    old "Sync downloaded."
    new "自动同步下载。"
    old "Could not connect to the Ren'Py Sync server."
    new "无法连接到Ren'Py同步服务器。"
    old "The Ren'Py Sync server timed out."
    new "连接Ren'Py同步服务器超时。"
    old "An unknown error occurred while connecting to the Ren'Py Sync server."
    new "连接到Ren'Py同步服务器时发生未知错误。"
    old "The Ren'Py Sync server does not have a copy of this sync. The sync ID may be invalid, or it may have timed out."
    new "Ren'Py同步服务器没有此设备的同步凭证。同步ID可能无效，或者链接已超时。"
    old "Please enter the sync ID you generated.\nNever enter a sync ID you didn't create yourself."
    new "请输入您自己生成的同步ID。\n切勿输入他人的同步ID。"
    old "The sync ID is not in the correct format."
    new "同步ID格式不正确。"
    old "The sync could not be decrypted."
    new "无法解密同步。"
    old "The sync belongs to a different game."
    new "您同步的存档不是当前游戏。"
    old "The sync contains a file with an invalid name."
    new "同步包含具有无效名称的文件。"
    old "This will upload your saves to the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}.\nDo you want to continue?"
    new "这将把您的存档上传到{a=https://sync.renpy.org}Ren'Py同步服务器{/a}。\n您确定要继续吗？"
    old "Enter Sync ID"
    new "请输入同步ID"
    old "This will contact the {a=https://sync.renpy.org}Ren'Py Sync Server{/a}."
    new "这一步将会连接{a=https://sync.renpy.org}Ren'Py同步服务器{/a}。"
    old "Sync Success"
    new "同步成功"
    old "The Sync ID is:"
    new "同步ID是:"
    old "You can use this ID to download your save on another device.\nThis sync will expire in an hour.\nRen'Py Sync is supported by {a=https://www.renpy.org/sponsors.html}Ren'Py's Sponsors{/a}."
    new "您可以使用此ID在另一台设备上下载您的存档。\n此同步存档将在一小时后过期。\nRen'Py同步功能由{a=https://www.renpy.org/sponsors.html}Ren'Py的赞助者{/a} 支持。"
    old "Sync Error"
    new "同步错误"
    old "Contacting App Store\nPlease Wait..."
    new "正在联系App Store\n请稍候……"
    old "No update methods found."
    new "未找到更新方法。"
    old "Could not download file list: "
    new "无法下载文件列表: "
    old "File list digest does not match."
    new "文件列表摘要不匹配。"
    old "An error is being simulated."
    new "正在推算错误。"
    old "Either this project does not support updating, or the update status file was deleted."
    new "此项目可能不支持更新功能，或者更新文件已被删除。"
    old "This account does not have permission to perform an update."
    new "此帐户没有执行更新的权限。"
    old "This account does not have permission to write the update log."
    new "此帐户没有写入更新日志的权限。"
    old "Could not verify update signature."
    new "无法验证更新签名。"
    old "The update file was not downloaded."
    new "未下载更新文件。"
    old "The update file does not have the correct digest - it may have been corrupted."
    new "更新文件没有正确的摘要 - 文件可能已损坏。"
    old "While unpacking {}, unknown type {}."
    new "在解压 {} 时，遇到未知类型文件 {}。"
    old "Updater"
    new "更新程序"
    old "An error has occured:"
    new "发生错误:"
    old "Checking for updates."
    new "正在检查更新。"
    old "This program is up to date."
    new "此程序已是最新版本。"
    old "[u.version] is available. Do you want to install it?"
    new "[u.version]可用。您要安装它吗？"
    old "Preparing to download the updates."
    new "准备下载更新。"
    old "Downloading the updates."
    new "正在下载更新。"
    old "Unpacking the updates."
    new "正在解压更新。"
    old "Finishing up."
    new "完成。"
    old "The updates have been installed. The program will restart."
    new "更新已安装。程序将重新启动。"
    old "The updates have been installed."
    new "更新已安装。"
    old "The updates were cancelled."
    new "更新已取消。"
    old "Proceed"
    new "继续"
    old "Preparing to download the game data."
    new "准备下载游戏数据。"
    old "Downloading the game data."
    new "正在下载游戏数据。"
    old "The game data has been downloaded."
    new "游戏数据已下载。"
    old "An error occured when trying to download game data:"
    new "尝试下载游戏数据时发生错误:"
    old "This game cannot be run until the game data has been downloaded."
    new "在游戏数据下载完成之前，您无法运行游戏。"
    old "Retry"
    new "重试"
    old "Image [index] of [count] locked."
    new "图像“[index]的[count]”已锁定。"
    old "prev"
    new "上一页"
    old "next"
    new "下一页"
    old "slideshow"
    new "幻灯片"
    old "return"
    new "返回"
    old "Renderer"
    new "渲染器"
    old "Automatically Choose"
    new "自动选择"
    old "Force GL Renderer"
    new "强制GL渲染器"
    old "Force ANGLE Renderer"
    new "强制ANGLE渲染器"
    old "Force GLES Renderer"
    new "强制GLES渲染器"
    old "Force GL2 Renderer"
    new "强制GL2 渲染器"
    old "Force ANGLE2 Renderer"
    new "强制ANGLE2 渲染器"
    old "Force GLES2 Renderer"
    new "强制GLES2 渲染器"
    old "Enable (No Blocklist)"
    new "启用（无阻止列表）"
    old "Powersave"
    new "节能"
    old "Framerate"
    new "帧率"
    old "Screen"
    new "屏幕"
    old "60"
    new "60"
    old "30"
    new "30"
    old "Tearing"
    new "撕裂"
    old "Changes will take effect the next time this program is run."
    new "更改将在下次运行此程序时生效。"
    old "Performance Warning"
    new "性能警告"
    old "This computer is using software rendering."
    new "此计算机正在使用软件渲染。"
    old "This game requires use of GL2 that can't be initialised."
    new "无法加载GL2，初始化未完成。"
    old "This computer has a problem displaying graphics: [problem]."
    new "此计算机的图形显示存在问题: [problem]。"
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "其图形驱动程序可能已过时或未正确运行。这可能导致图形显示缓慢或显示错误。"
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new "{a=edit:1:log.txt}log.txt{/a}文件可能包含帮助您确定出现的计算机问题。"
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new "有关如何修复此问题的更多详细信息，请参阅 {a=[url]}文档{/a}。"
    old "Continue, Show this warning again"
    new "继续，若问题再次发生，再次提醒我"
    old "Continue, Don't show warning again"
    new "继续，不再显示此类警告"
    old "Change render options"
    new "更改渲染选项"
    old "Select Gamepad to Calibrate"
    new "选择要校准的游戏手柄"
    old "No Gamepads Available"
    new "无可用游戏手柄"
    old "Calibrating [name] ([i]/[total])"
    new "校准[name] ([i]/[total])"
    old "Press or move the '[control!s]' [kind]."
    new "按下或移动 '[control!s]' [kind]。"
    old "Skip (A)"
    new "跳过 (A)"
    old "Back (B)"
    new "返回 (B)"
    old "Open"
    new "打开"
    old "Opens the traceback.txt file in a text editor."
    new "在文本编辑器中打开traceback.txt文件。"
    old "Copy BBCode"
    new "复制BBCode"
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new "将traceback.txt文件复制到剪贴板，作为BBcode用于论坛，如https://lemmasoft.renai.us/。"
    old "Copy Markdown"
    new "复制Markdown"
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new "将traceback.txt文件复制到剪贴板，作为Markdown用于Discord。"
    old "An exception has occurred."
    new "发生异常。"
    old "Rollback"
    new "回退"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "尝试回退游戏进度，方便您存档或者选择其他选项。"
    old "Ignore"
    new "忽略"
    old "Ignores the exception, allowing you to continue."
    new "忽略异常，继续游戏。"
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "忽略异常，继续继续。可能会产生其他错误。"
    old "Reload"
    new "重新加载"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "恢复游戏，并尽可能还原游戏进度。"
    old "Console"
    new "控制台"
    old "Opens a console to allow debugging the problem."
    new "打开控制台以允许调试问题。"
    old "Quits the game."
    new "退出游戏。"
    old "Parsing the script failed."
    new "解析脚本失败。"
    old "high contrast text"
    new "高对比度文本"
    old "reset"
    new "重置"
    old "Translation identifier: [identifier]"
    new "翻译标识:[identifier]"
    old " translates [tl.filename]:[tl.linenumber]"
    new " 翻译[tl.filename]:[tl.linenumber]"
    old "\n{color=#fff}Copied to clipboard.{/color}"
    new "\n{color=#fff}已复制至剪贴板{/color}"
    # renpy/common/000statements.rpy:28
    old "Click to play the video."
    new "点击播放视频"

    # renpy/common/00accessibility.rpy:180
    old "Mono Audio"
    new "单声道音频"

    # renpy/common/00accessibility.rpy:246
    old "Kerning"
    new "字距"

    # renpy/common/00accessibility.rpy:288
    old "Self-Voicing and Audio"
    new "自动语音和音频"

    # renpy/common/00accessibility.rpy:292
    old "Text"
    new "文本"

    # renpy/common/00preferences.rpy:602
    old "mono audio"
    new "单声道音频"

    # renpy/common/00preferences.rpy:611
    old "font kerning"
    new "字距"

    # renpy/common/00updater.rpy:1935
    old "An error has occurred:"
    new "出现错误："

    # renpy/common/00updater.rpy:1992
    old "An error occurred when trying to download game data:"
    new "下载游戏数据时出现错误："
