translate zh_hans strings:

    old "{space=50}{rb} {/rb}{rt}{pen=yellow}{size=+11}... she was totally giving him a boobjob!{/size}{/pen}{pen=purple}{size=+30}  {b}{k=-25}x_x{/k}{/b}{/size}{/pen}{/rt}"
    new "{space=50}{rb} {/rb}{rt}{pen=yellow}{size=+11}……她居然在给他乳交！{/size}{/pen}{pen=purple}{size=+30}  {b}{k=-25}x_x{/k}{/b}{/size}{/pen}{/rt}"

    old "{pen=blue}the {pen=neonpink}best dick {i}ever{/i}{/pen} {rt}{pen=indigo}{size=-10}{b}{i}SO GOOD{/i}{/b}{/size}{/pen}{/rt}and she's obviously all {pen=indigo}pen{size=-10}t{/size} up{/pen}.{/pen}{rt}{pen=blue}{size=-3} and {pen=neonpink}sexually frustrated!{/pen}{/size}{/pen}{/rt}{space=25}"
    new "{pen=blue}史上{pen=neonpink}最棒{i}的鸡巴{/i}{/pen} {rt}{pen=indigo}{size=-10}{b}{i}太爽了{/i}{/b}{/size}{/pen}{/rt}而且她显然{pen=indigo}憋{size=-10}坏{/size}了{/pen}。{/pen}{rt}{pen=blue}{size=-3} 还{pen=neonpink}欲求不满！{/pen}{/size}{/pen}{/rt}{space=25}"
    old "{pen=purple}{size=-2}Ugh, I hope this doesn't{/size} {size=-6}{pen=black}{b}kill{/b}{/pen} my camming {rb}career{/rb}{rt}{pen=pink}{size=-2}this {u}blows{/u} on so many levels{i}!{/i}{/size}{/pen}{/rt}{/size}..{/pen}{space=30}{art}{pen=indigo}{size=+4}wait...{/size}{/pen}{/art}"
    new "{pen=purple}{size=-2}呃，我希望这不会{/size} {size=-6}{pen=black}{b}毁掉{/b}{/pen}我的直播{rb}事业{/rb}{rt}{pen=pink}{size=-2}这可真是{u}糟透了{/u}{i}！{/i}{/size}{/pen}{/rt}{/size}……{/pen}{space=30}{art}{pen=indigo}{size=+4}等等……{/size}{/pen}{/art}"
    old "{pen=black}Am I going {pen=purple}{b}insane{/b}{/pen}?!{/pen}{art}{pen=black}I just have {pen=purple}this {pen=pink}{size=+5}insatiable {pen=neonpink}need{/pen}...{/size}{/pen}{/pen}{/pen}{space=100}{rt}{pen=black}{size=-4}Maybe I am?!{/size}{/pen}{/rt}"
    new "{pen=black}我是不是{pen=purple}{b}疯了{/b}{/pen}？！{/pen}{art}{pen=black}我就是有{pen=purple}一股{pen=pink}{size=+5}怎么都填不满的{pen=neonpink}欲望{/pen}……{/size}{/pen}{/pen}{/pen}{space=100}{rt}{pen=black}{size=-4}也许我真的疯了？！{/size}{/pen}{/rt}"
    old "{pen=pink}Hopefully they will take my mind off {pen=indigo}{b}[saga.cast.anon]{/b}'s {rb}{u}cock{/u}{/rb}{art}{pen=pink}¦D~~~{/pen}{/art}{/pen}.{/pen}{space=55}{rt}{pen=purple}{size=-10}{b}D{/b}{/size}roooo{size=-10}{b}L!{/b}{/size}{/pen}{/rt}"
    new "{pen=pink}希望它们能让我不再想{pen=indigo}{b}[saga.cast.anon]{/b}的{rb}{u}鸡巴{/u}{/rb}{art}{pen=pink}¦D~~~{/pen}{/art}{/pen}.{/pen}{space=55}{rt}{pen=purple}{size=-10}{b}口{/b}{/size}水直{size=-10}{b}流！{/b}{/size}{/pen}{/rt}"
    old "{space=80}{pen=purple}but honestly, {pen=neonpink}it was a lot of fun...{/pen}{/pen}{rb}{space=100}{/rb}{rt}{pen=indigo}{size=-3}and kinda {pen=neonpink}hot{/pen}, tbh. {size=+20}>{/size}-{size=+20}>{/size}{size=+10};;{/size}{/size}{/pen}{/rt}"
    new "{space=80}{pen=purple}不过说实话，{pen=neonpink}那真的很有趣……{/pen}{/pen}{rb}{space=100}{/rb}{rt}{pen=indigo}{size=-3}而且说实话，还挺{pen=neonpink}刺激{/pen}的。{size=+20}>{/size}-{size=+20}>{/size}{size=+10};;{/size}{/size}{/pen}{/rt}"
    old "{pen=orange}{size=+1}{b}[saga.cast.debbie]{/b}'s really been strugg{rb}ling with the entire situation.{/rb}{art}{pen=pink}{i}I totally {pen=maroon}knew{/pen} they were {pen=neonpink}{b}BONING{/b}!!!{/pen}{/i}{/pen}{/art}{/size}{/pen}"
    new "{pen=orange}{size=+1}{b}[saga.cast.debbie]{/b}因为这一切一直{rb}很不好受。{/rb}{art}{pen=pink}{i}我就{pen=maroon}知道{/pen}他们俩{pen=neonpink}{b}搞在一起了{/b}！！！{/pen}{/i}{/pen}{/art}{/size}{/pen}"
    old "{pen=purple}I wonder {rb}what {space=5}{pen=navy}{size=+6}{b}two{/b}{/size}{/pen} vibrators would feel like?{/rb}{art}{pen=neonpink}{size=-4}{b}AH!{/b} {pen=pink}My kitty is twitching just imagining it!{/pen}{/size}{/pen}{/art}{/pen}"
    new "{pen=purple}真想知道{rb}{space=5}{pen=navy}{size=+6}{b}两个{/b}{/size}{/pen}振动棒一起用是什么感觉？{/rb}{art}{pen=neonpink}{size=-4}{b}啊！{/b} {pen=pink}一想到这我的小穴就一抽一抽的！{/pen}{/size}{/pen}{/art}{/pen}"
    old "{rb}{pen=purple}I've {pen=neonpink}{u}ALWAYS{/u}{/pen} wanted to try one!{/pen}{/rb}{art}{size=-4}{pen=neonpink}Mmmmm! I'm like, actually panting with excitement rn... {pen=red}fuuuuck!{/pen}{/pen}{/size{{/art}{space=80}"
    new "{rb}{pen=purple}我{pen=neonpink}{u}一直{/u}{/pen}想试一个！{/pen}{/rb}{art}{size=-4}{pen=neonpink}嗯～！我现在简直兴奋得要喘不过气来……{pen=red}操！{/pen}{/pen}{/size{{/art}{space=80}"
    old "{pen=blue}I told her I would think about it... {rb}{pen=navy}{b}YEAH RIGHT{/b}{/pen}!{/rb}{art}{pen=navy}Can you even imagine? {pen=aqua}{size=+2}{b}{i}{u}SO{/u}{/i}{/b} boring!{/size}{/pen}{/pen}{/art}{/pen}{space=30}"
    new "{pen=blue}我跟她说我会考虑一下……{rb}{pen=navy}{b}想得美{/b}{/pen}！{/rb}{art}{pen=navy}你能想象吗？{pen=aqua}{size=+2}{b}{i}{u}太{/u}{/i}{/b}无聊了！{/size}{/pen}{/pen}{/art}{/pen}{space=30}"
    old "{pen=maroon}OMG I just walked in on {pen=navy}[saga.cast.debbie]{/pen} {pen=black}{b}KISSING{/b}{/pen} [saga.cast.anon]...{/pen}{space=40}{rt}{pen=black}{size=-3}with her{/size} {pen=pink}TONGUE!!!{/pen}{/pen}{/rt}"
    new "{pen=maroon}天啊，我刚刚撞见{pen=navy}[saga.cast.debbie]{/pen}{pen=black}{b}吻着{/b}{/pen}[saga.cast.anon]……{/pen}{space=40}{rt}{pen=black}{size=-3}还用了{/size} {pen=pink}舌头！！！{/pen}{/pen}{/rt}"
    old "{pen=indigo}Just thinking about it feels... {pen=pink}{size=-2}{rb}feels{/rb}{art}{pen=indigo}{size=+2}I mean it was {pen=silver}{b}CRAZY{/b}!{/pen}{/size}{/pen}{/art} so.......{/size}{/pen}{/pen}{space=20}"
    new "{pen=indigo}光是想想就觉得……{pen=pink}{size=-2}{rb}觉得{/rb}{art}{pen=indigo}{size=+2}那真是太{pen=silver}{b}疯狂了{/b}！{/pen}{/size}{/pen}{/art}好……{/size}{/pen}{/pen}{space=20}"
    old "{pen=neonpink}{size=-2}I swallowed him... his {pen=pink}{size=+20}{b}cum{/b}{/size}{/pen}... everything...{/size}{/pen}{space=70}{rt}{pen=maroon}{size=-3}WHY DID I DO THAT?!{/size}{/pen}{/rt}{space=30}"
    new "{pen=neonpink}{size=-2}我把他……他的{pen=pink}{size=+20}{b}精液{/b}{/size}{/pen}……全吞下去了……{/size}{/pen}{space=70}{rt}{pen=maroon}{size=-3}我为什么要那样做？！{/size}{/pen}{/rt}{space=30}"
    old "{pen=maroon}She says she's {pen=yellow}{size=-3}\"helping him with anxieties\"{/size}{/pen} {rb}or some{/rb}{rt}{pen=indigo}{size=+2}{i}Yeah right!{/i}{/size}{/pen}{/rt} {b}bullshit{/b}.{/pen}{space=35}"
    new "{pen=maroon}她说她在{pen=yellow}{size=-3}“帮他缓解焦虑”{/size}{/pen} {rb}之类的{/rb}{rt}{pen=indigo}{size=+2}{i}信她才怪！{/i}{/size}{/pen}{/rt} {b}鬼话{/b}。{/pen}{space=35}"
    old "{pen=indigo}his {pen=neonpink}{u}cum all over her{/u}{rt}{pen=neonpink}face!!{/pen}{/rt}{/pen}, and proceeded to have a full on{/pen}{vspace=0}{space=430}{pen=indigo}{size=-8}crash out!{/size}{/pen}"
    new "{pen=indigo}他的{pen=neonpink}{u}精液沾得她{/u}{rt}{pen=neonpink}满脸{/pen}{/rt}{/pen}都是！！然后就彻底{/pen}{vspace=0}{space=430}{pen=indigo}{size=-8}崩溃了！{/size}{/pen}"
    old "{pen=orange}{rb}What a{/rb}{art}{pen=red}{size=-1}So {pen=maroon}{size=+8}{u}thirsty{/u}{/size}{/pen}! It's {b}just sad.{/b} LOL!{/size}{/pen}{/art} {pen=red}{b}LOSER{/b}{/pen}!!{/pen}{space=100}"
    new "{pen=orange}{rb}真是{/rb}{art}{pen=red}{size=-1}太{pen=maroon}{size=+8}{u}饥渴{/u}{/size}{/pen}了！真是{b}可悲。{/b}哈哈哈！{/size}{/pen}{/art} {pen=red}{b}废柴{/b}{/pen}！！{/pen}{space=100}"
    old "{pen=pink}{size=-2}Only when I imagined it, he was {pen=purple}good looking{/pen} and {pen=indigo}suave...{/pen}{/size}{/pen}{rt}{pen=pink}and {pen=navy}filthy rich!{/pen}{/pen}{/rt}{space=25}"
    new "{pen=pink}{size=-2}不过我想象中的他可是{pen=purple}长得帅{/pen}，还{pen=indigo}风度翩翩……{/pen}{/size}{/pen}{rt}{pen=pink}而且还{pen=navy}腰缠万贯！{/pen}{/pen}{/rt}{space=25}"
    old "{pen=aqua}{size=-2}Eugh, {pen=blue}{b}[saga.cast.debbie]{/b}{/pen} and {pen=blue}{b}[saga.cast.anon]{/b}{/pen} are fucking... So {pen=maroon}{size=-5}{b}GROSS!!!{/b}{/size}{/pen}{/size}{/pen}"
    new "呃，{pen=aqua}{size=-2}{pen=blue}{b}[saga.cast.debbie]{/b}{/pen}和{pen=blue}{b}[saga.cast.anon]{/b}{/pen}在干炮……太{pen=maroon}{size=-5}{b}恶心了！！！{/b}{/size}{/pen}{/size}{/pen}"
    old "{pen=pink}That little virgin is hung like a fucking {pen=maroon}{b}MOO{rb}SE{/rb}{art}{pen=purple}it was {pen=neonpink}{size=-5}{b}{u}HUGE{/u}{/b}!!!{/size}{/pen}{/pen}{/art}{/b}{/pen}!{/pen}"
    new "{pen=pink}那个小处男的鸡巴居然大得像他妈的{pen=maroon}{b}驼{rb}鹿{/rb}{art}{pen=purple}，那玩意儿{pen=neonpink}{size=-5}{b}{u}巨大{/u}{/b}！！！{/size}{/pen}{/pen}{/art}{/b}{/pen}！{/pen}"
    old "{pen=indigo}{size=-5}mother {pen=neonpink}{size=-2}{b}\"HELPING\"{/b}{/size}{/pen} him again{rb}...{/rb}{rt}{pen=aqua}{size=-10}{b}AS FUCKING IF!!{/b}{/size}{/pen}{/rt}{/size}{/pen}{space=100}"
    new "{pen=indigo}{size=-5}妈妈又在{pen=neonpink}{size=-2}{b}“帮”{/b}{/size}{/pen}他来着{rb}……{/rb}{rt}{pen=aqua}{size=-10}{b}谁他妈信啊！！{/b}{/size}{/pen}{/rt}{/size}{/pen}{space=100}"
    old "{pen=purple}I gave him the {rb}option - leer at them... {pen=pink}for a price!{/pen}{/rb}{art}{pen=indigo}{size=+1}He couldn't believe it lol, his face was so derpy!{/size}{/pen}{/art}{/pen}"
    new "{pen=purple}我给了他个{rb}选择——想看这些照片也行……{pen=pink}不过得掏钱！{/pen}{/rb}{art}{pen=indigo}{size=+1}他简直不敢相信，哈哈，他的表情傻透了！{/size}{/pen}{/art}{/pen}"
    old "{pen=silver}{size=-2}The truth is...{/size}{space=20}I {pen=neonpink}{size=+3}{i}wanted{/i}{/size}{/pen} to do it...{/pen}{space=20}{pen=neonpink}{size=-5}{b}WTF?!{/b}{/size}{/pen}{space=40}"
    new "{pen=silver}{size=-2}事实上……{/size}{space=20}我{pen=neonpink}{size=+3}{i}想{/i}{/size}{/pen}这么做……{/pen}{space=20}{pen=neonpink}{size=-5}{b}什么鬼？！{/b}{/size}{/pen}{space=40}"
    old "{pen=maroon}{size=+4}my {pen=orange}{b}child{/b}{/pen} in my arms for the first time...{/size}{/pen}{space=90}{rt}{pen=silver}{size=-6}being this happy is {u}so{/u} weird!{/size}{/pen}{/rt}"
    new "{pen=maroon}{size=+4}第一次把我的{pen=orange}{b}孩子{/b}{/pen}抱在怀里的时候……{/size}{/pen}{space=90}{rt}{pen=silver}{size=-6}这么幸福真是{u}太{/u}奇怪了！{/size}{/pen}{/rt}"
    old "{rb}{pen=lime}OH MY GOD! I would {pen=black}totally {b}DIE{/b}!{/pen}{/pen}{/rb}{art}{pen=maroon}Maybe I should make him {pen=purple}wear a mask{/pen} or something?{/pen}{/art}{space=50}"
    new "{rb}{pen=lime}哦我的天！我{pen=black}绝对{b}会{/b}死{/pen}的！{/pen}{/rb}{art}{pen=maroon}也许我应该让他{pen=purple}戴个面具{/pen}什么的？{/pen}{/art}{space=50}"
    old "{pen=orange}{size=-4}... and what if he gets all {pen=red}{b}possessive{/b}{/pen} like {pen=maroon}{b}[saga.cast.cedric]{/b}{/pen}?!{/size}{/pen}{art}{pen=orange}Fuck. That.{/pen}{/art}"
    new "{pen=orange}{size=-4}……要是他也变得{pen=red}{b}占有欲那么强{/b}{/pen}，就像{pen=maroon}{b}[saga.cast.cedric]{/b}{/pen}那样？！{/size}{/pen}{art}{pen=orange}去他妈的。想都别想。{/pen}{/art}"
    old "{pen=aqua}{size=-1}This adorable {pen=yellow}little creature{/pen} that's part {pen=neonpink}{size=+4}me{/size}{/pen} and part {pen=purple}{b}[saga.cast.anon]{/b}{/pen}.{/size}{/pen}"
    new "{pen=aqua}{size=-1}这个可爱的{pen=yellow}小生物{/pen}，一部分是{pen=neonpink}{size=+4}我{/size}{/pen}，另一部分是{pen=purple}{b}[saga.cast.anon]{/b}{/pen}。{/size}{/pen}"
    old "{pen=pink}{b}[saga.cast.anon]{/b} caught me watching {rb}porn in the living room tonight.{/rb}{art}{pen=pink}He's such a {pen=red}{b}fucking {u}loser{/u}!{/b}{/pen}{/pen}{/art}{/pen}"
    new "{pen=pink}{b}[saga.cast.anon]{/b}今晚撞见我在客厅看{rb}黄片。{/rb}{art}{pen=pink}他真是个{pen=red}{b}该死的{u}废柴{/u}！{/b}{/pen}{/pen}{/art}{/pen}"
    old "{space=75}{pen=pink}{pen=silver}{b}[saga.cast.debbie]{/b}{/pen} is going to kill me...{/pen}{space=75}{rt}{pen=blue}{size=-2}What do I {i}even{/i} {u}tell{/u} her?!{/size}{/pen}{/rt}"
    new "{space=75}{pen=pink}{pen=silver}{b}[saga.cast.debbie]{/b}{/pen}会杀了我……{/pen}{space=75}{rt}{pen=blue}{size=-2}我到底要怎么{i}跟{/i} {u}她说{/u}？！{/size}{/pen}{/rt}"
    old "{pen=indigo}{size=-3}think about is {pen=neonpink}that {size=+3}ridiculously{/size} {pen=red}{size=-8}{b}ENORMOUS{/b}{/size}{/pen} cock{/pen} in his pants...{/size}{/pen}{space=15}"
    new "{pen=indigo}{size=-3}我脑子里就全是{pen=neonpink}他裤裆里那根{size=+3}大得{/size}{pen=red}{size=-8}{b}离谱的{/b}{/size}{/pen}肉棒{/pen}……{/size}{/pen}{space=15}"
    old "{pen=orange}I'm {pen=maroon}super excited{/pen} but it's {pen=red}so big{/pen}...{rb}{space=20}{/rb}{rt}{pen=pink}{size=-3}hope it {size=+5}fits{/size}!!{/size}{/pen}{/rt}{/pen}"
    new "{pen=orange}我{pen=maroon}超级兴奋{/pen} 但是它{pen=red}好大{/pen}……{rb}{space=20}{/rb}{rt}{pen=pink}{size=-3}希望它{size=+5}塞得进去{/size}！！{/size}{/pen}{/rt}{/pen}"
    old "{pen=silver}Then next minute {pen=neonpink}my feet were covered{/pen} and{rb}... {size=-4}I didn't hate it.{/size}{/rb}{art}{pen=silver}What's wrong with me?!{/pen}{/art}{/pen}"
    new "{pen=silver}然后下一秒{pen=neonpink}我的脚就被弄得一塌糊涂{/pen}，而且{rb}……{size=-4}我居然不讨厌。{/size}{/rb}{art}{pen=silver}我这是怎么了？！{/pen}{/art}{/pen}"
    old "{pen=pink}{size=-2}You're {pen=neonpink}fucking a hot {rb}ass-girl{/rb}{rt}{pen=purple}{size=-1}me, obv{/size}{/pen}{/rt}{/pen} and they are paying you to do it.{/size}{/pen}"
    new "{pen=pink}{size=-2}你{pen=neonpink}正在和一个辣妹{rb}干炮{/rb}{rt}{pen=purple}{size=-1}当然是我咯{/size}{/pen}{/rt}{/pen}而且他们还付钱让你干。{/size}{/pen}"
    old "{space=30}{pen=maroon}He's such a {pen=red}doofus{/pen} and he says the dumbest {rb}things{/rb}{art}{pen=aqua}{size=-5}{b}ALL THE {u}TIME{/u}!{/b}{/size}{/pen}{/art}...{/pen}"
    new "{space=30}{pen=maroon}他真是个{pen=red}傻瓜{/pen}，还总说些最蠢的{rb}话{/rb}{art}{pen=aqua}{size=-5}{b}每时每刻{u}都在说{/u}！{/b}{/size}{/pen}{/art}……{/pen}"
    old "{space=20}{pen=blue}I can finally give {pen=navy}{b}[saga.cast.debbie]{/b}{/pen} some money{rt}{pen=navy}and get her {size=+3}off my back{/size}!{/pen}{/rt}{/pen}{space=80}"
    new "{space=20}{pen=blue}我终于可以给{pen=navy}{b}[saga.cast.debbie]{/b}{/pen}一些钱{rt}{pen=navy}，让她{size=+3}别再烦我了{/size}！{/pen}{/rt}{/pen}{space=80}"
    old "{pen=maroon}{size=-3}And the few who aren't, are too {pen=black}{size=+10}fat{/size}{/pen} or {pen=black}ugly{/pen} to bring in {pen=pink}any fans{/pen}!{/size}{/pen}"
    new "{pen=maroon}{size=-3}难得有几个不怂的，又太{pen=black}{size=+10}胖{/size}{/pen}或{pen=black}丑{/pen}，根本带不来{pen=pink}任何粉丝{/pen}！{/size}{/pen}"
    old "{pen=purple}{size=-2}I could have crashed at his place until I found a {rb}way to make{/rb}{art}{pen=indigo}{size=+0}{b}BIG BUCKS!{/b}{/size}{/pen}{/art}{/size}{/pen}"
    new "{pen=purple}{size=-2}我本可以住在他那儿，直到我找到{rb}一个赚{/rb}{art}{pen=indigo}{size=+0}{b}大钱的方法！{/b}{/size}{/pen}{/art}{/size}{/pen}"
    old "{space=50}{pen=purple}{size=-6}The {pen=aqua}little perv{/pen} probably told her some {pen=aqua}{b}sob story{/b}{/pen} about his {pen=aqua}pathetic{/pen}{/size}{/pen}"
    new "{space=50}{pen=purple}{size=-6}那{pen=aqua}小变态{/pen}大概又在{pen=aqua}{b}卖惨{/b}{/pen}，说自己过着{pen=aqua}可怜巴巴的{/pen}{/size}{/pen}"
    old "{pen=aqua}Momma got herself a {pen=lime}{size=-5}{b}BAD MONSTER{/b}{/size}{/pen} today!{art}{pen=blue}{size=-3}{b}FUCK YEAH!!!{/b}{/size}{/pen}{/art}{/pen}{space=50}"
    new "{pen=aqua}老娘今天入手了一个{pen=lime}{size=-5}{b}坏怪物{/b}{/size}{/pen}！{art}{pen=blue}{size=-3}{b}太他妈爽了！！！{/b}{/size}{/pen}{/art}{/pen}{space=50}"
    old "{pen=pink}I could lie and say it was {pen=aqua}the money{/pen}{/pen}{space=50}{rt}{pen=pink}there was a {pen=red}{size=-3}{b}{i}LOT!!{/i}{/b}{/size}{/pen}{/pen}{/rt}"
    new "{pen=pink}我可以撒谎说是因为{pen=aqua}钱{/pen}{/pen}{space=50}{rt}{pen=pink}真的{pen=red}{size=-3}{b}{i}很多很多！！{/i}{/b}{/size}{/pen}{/pen}{/rt}"
    old "{pen=indigo}{size=-2}with this crappy {i}\"lite\"{/i} version! It's a total {pen=red}{size=-6}{b}PIECE OF {size=+16}{u}SHIT{/u}!{/size}{/b}{/size}{/pen}{/size}{/pen}"
    new "{pen=indigo}{size=-2}这个破{i}“轻量”{/i}版！简直是一{pen=red}{size=-6}{b}坨{size=+16}{u}屎{/u}！{/size}{/b}{/size}{/pen}{/size}{/pen}"
    old "{pen=purple}{size=-3}... that{/size}{/pen} {size=+12}{pen=indigo}{b}HUGE{/b}{/pen} {pen=neonpink}{b}HARD{/b}{/pen} {pen=navy}{b}COCK{/b}{/pen}{/size}{space=100}"
    new "{pen=purple}{size=-3}…… 那根{/size}{/pen} {size=+12}{pen=indigo}{b}又粗又大{/b}{/pen} {pen=neonpink}{b}硬邦邦的{/b}{/pen} {pen=navy}{b}鸡巴{/b}{/pen}{/size}{space=100}"
    old "{pen=purple}she probably found it looking for hook-{rb}ups.{space=75}{/rb}{rt}{pen=neonpink}{size=-5}she's always been a {b}SLUT{/b}!{/size}{/pen}{/rt}{/pen}"
    new "{pen=purple}她可能是在找炮{rb}友的时候发现这个的。{space=75}{/rb}{rt}{pen=neonpink}{size=-5}她一直是个{b}荡妇{/b}！{/size}{/pen}{/rt}{/pen}"
    old "{pen=blue}I'm{/pen} {pen=indigo}thinking{/pen} {pen=purple}something{/pen} {pen=red}by{/pen} {pen=orange}the{/pen} {pen=yellow}{size=+12}beach!{/size}{/pen}"
    new "{pen=blue}我{/pen}{pen=indigo}想{/pen}{pen=purple}找套{/pen}{pen=red}海{/pen}{pen=orange}边{/pen}{pen=yellow}{size=+12}的！{/size}{/pen}"
    old "{pen=maroon}{size=-6}Maybe I can even turn on the waterworks{vspace=0}and guilt {b}[saga.cast.debbie]{/b} into buying me a camera?{/size}{/pen}{space=100}"
    new "{pen=maroon}{size=-6}说不定我再挤几滴眼泪{vspace=0}，让{b}[saga.cast.debbie]{/b}一内疚，就给我买台相机？{/size}{/pen}{space=100}"
    old "{pen=pink}{size=-3}How could I be so {pen=indigo}{size=-7}{b}FUCKING{/b}{/size}{/pen} {pen=purple}{size=+7}stupid{/size}{/pen}?!{/size}{/pen}{space=140}"
    new "{pen=pink}{size=-3}我怎么会这么{pen=indigo}{size=-7}{b}他妈{/b}{/size}{/pen} {pen=purple}{size=+7}蠢{/size}{/pen}？！{/size}{/pen}{space=140}"
    old "{pen=silver}{size=-4}It's not even just about him!{/size} I don't want a {pen=blue}boyfriend{/pen}, {pen=navy}{size=-5}{b}PERIOD!{/b}{/size}{/pen}{/pen}"
    new "{pen=silver}{size=-4}这又不只是他的问题！{/size} 我压根就不想交{pen=blue}男朋友{/pen}，{pen=navy}{size=-5}{b}就这么简单！{/b}{/size}{/pen}{/pen}"
    old "OMG, you're not going to believe this! [saga.cast.odette] is pregnant! I just overheard her and my sister talking about it. I wonder who the father is?"
    new "天啊，你绝对不会相信这个！[saga.cast.odette]怀孕了！我刚偷听到她和我姐姐在谈论这件事。不知道孩子的父亲是谁？"
    old "{pen=orange}He apparently {pen=silver}has feelings for me...{/pen}{rt}{pen=orange}what a {pen=neonpink}little girl!{/pen}{/pen}{/rt}{/pen}{space=100}"
    new "{pen=orange}他显然{pen=silver}对我有感觉……{/pen}{rt}{pen=orange}真是个{pen=neonpink}小丫头！{/pen}{/pen}{/rt}{/pen}{space=100}"
    old "{pen=blue}I get why {pen=navy}{b}[saga.cast.debbie]{/b}{/pen} is doing it. {pen=navy}{b}[saga.cast.anon]{/b}{/pen} has like, well...{/pen}{space=30}"
    new "{pen=blue}我明白为什么{pen=navy}{b}[saga.cast.debbie]{/b}{/pen}会这么做。{pen=navy}{b}[saga.cast.anon]{/b}{/pen}那根可是，怎么说呢……{/pen}{space=30}"
    old "{pen=purple}{size=-2}I was {pen=neonpink}{i}super{/i} horny{/pen} and his dick was already {pen=neonpink}{i}super{/i} hard{/pen} and...{/size}{/pen}"
    new "{pen=purple}{size=-2}我{pen=neonpink}{i}超级{/i}饥渴{/pen}，他的鸡巴已经{pen=neonpink}{i}超级{/i}硬{/pen}了，然后……{/size}{/pen}"
    old "{space=40}{pen=blue}Don't I at least deserve {pen=navy}{b}{u}THAT{/u}{/b}{/pen}?{/pen}{space=20}{pen=aqua}{size=-3}I'm like, super hot!{/size}{/pen}"
    new "{space=40}{pen=blue}我至少也该有{pen=navy}{b}{u}这个{/u}{/b}{/pen}吧？{/pen}{space=20}{pen=aqua}{size=-3}我可是超级性感！{/size}{/pen}"
    old "{pen=indigo}I mean... {pen=blue}{size=-2}{b}perverts{/b}{/size}{/pen} are into {pen=neonpink}{size=+2}pregnant chicks{/size}{/pen}... right?!{/pen}"
    new "{pen=indigo}我的意思是……{pen=blue}{size=-2}{b}变态{/b}{/size}{/pen}喜欢{pen=neonpink}{size=+2}孕妇{/size}{/pen}……对吧？！{/pen}"
    old "{pen=blue}{size=+3}He's so pathetic! I bet he's still a {pen=navy}{size=-10}{b}{u}{k=3.}VIRGIN{/k}{/u}{/b}{/size}{/pen}...{/pen}{/size}{space=30}"
    new "{pen=blue}{size=+3}他好可悲啊！我敢打赌他还是个{pen=navy}{size=-10}{b}{u}{k=3.}处男{/k}{/u}{/b}{/size}{/pen}……{/pen}{/size}{space=30}"
    old "{pen=purple}{size=-1}I {pen=blue}{i}suppose{/i}{/pen} I can get a buttplug... {pen=black}{b}{i}if{/i}{/b}{/pen} they keep paying me!{/size}{/pen}"
    new "{pen=purple}{size=-1}我{pen=blue}{i}想{/i}{/pen}可以弄个肛塞……{pen=black}{b}{i}只要{/i}{/b}{/pen}他们继续给我付钱！{/size}{/pen}"
    old "{pen=purple}{size=-2}She still thinks I quit...{space=15}{pen=red}{size=-6}There is NO WAY I'm telling her I got fired!{/size}{/pen}{/size}{/pen}"
    new "{pen=purple}{size=-2}她还以为我辞职了……{space=15}{pen=red}{size=-6}我可绝对不能告诉她我被炒了！{/size}{/pen}{/size}{/pen}"
    old "{pen=orange}{size=-3}I don't even know anymore... It's just been a {pen=yellow}{size=+4}{i}{u}super{/u}{/i}{/size}{/pen} weird day!{/size}{/pen}"
    new "{pen=orange}{size=-3}我已经不知道了…… 这真是{pen=yellow}{size=+4}{i}{u}超级{/u}{/i}{/size}{/pen}奇怪的一天！{/size}{/pen}"
    old "{pen=purple}{size=-4}He may have been a {k=1.8}{pen=red}{b}MEAT{/b}{/pen}{pen=orange}HEAD{/k}{/pen} but at least he was obedient...{/size}{/pen}"
    new "{pen=purple}{size=-4}他是个{k=1.8}{pen=red}{b}肌肉{/b}{/pen}{pen=orange}白痴{/k}{/pen}没错，但至少他很听话……{/size}{/pen}"
    old "{pen=purple}{size=-4}Like she doesn't get enough {pen=orange}{u}dick{/u}{/pen} at her {pen=indigo}{b}SEX ADDICTS{/b}{/pen} group...{/size}{/pen}"
    new "{pen=purple}{size=-4}好像她在{pen=indigo}{b}性瘾者互助小组{/b}{/pen}里{pen=orange}{u}鸡巴{/u}{/pen}还没吃够似的……{/size}{/pen}"
    old "{pen=blue}{size=-3}Why can't I find a fa{rb}mous guy{/rb}{rt}{pen=black}{size=+2}i.e. rich{/size}{/pen}{/rt} to take care of me??!{/size}{/pen}"
    new "{pen=blue}{size=-3}我怎么就找不到一个出{rb}名的男人{/rb}{rt}{pen=black}{size=+2}也就是有钱人{/size}{/pen}{/rt}来照顾我呢？！{/size}{/pen}"
    old "{pen=aqua}I had {pen=navy}{b}[saga.cast.anon]{/b}{/pen} take some {pen=neonpink}{size=+3}naughty pictures{/size}{/pen} of me to post...{/pen}"
    new "{pen=aqua}我让{pen=navy}{b}[saga.cast.anon]{/b}{/pen}拍了一些我的{pen=neonpink}{size=+3}香艳照片{/size}{/pen}来发布……{/pen}"
    old "{pen=black}{size=-9}{b}{pen=navy}VIBRATOR{/pen} + {pen=indigo}BUTTPLUG{/pen} = {pen=neonpink}MIND SHATTERING ORGASM!!!{/pen}{/b}{/size}{/pen}"
    new "{pen=black}{size=-9}{b}{pen=navy}震动棒{/pen} + {pen=indigo}肛塞{/pen} = {pen=neonpink}高潮爽翻天！！！{/pen}{/b}{/size}{/pen}"
    old "{pen=blue}{b}{size=-6}FUCK{pen=purple}{b}ME{pen=indigo}{b}HOLY{pen=navy}{b}SHIT!{/b}{/pen}!{/b}{/pen}!{/b}{/pen}!{/b}{/size}{/pen}{space=100}"
    new "{pen=blue}{b}{size=-6}操{pen=purple}{b}我{pen=indigo}{b}天{pen=navy}{b}呐！{/b}{/pen}！{/b}{/pen}！{/b}{/pen}！{/b}{/size}{/pen}{space=100}"
    old "{pen=indigo}{size=-3}I sent him to {pen=neonpink}{b}Pink{/b}{/pen} for an {pen=navy}{b}Electro Clit{/b}{/pen} and he comes back{/size}{/pen}"
    new "{pen=indigo}{size=-3}我叫他去{pen=neonpink}{b}粉色诱惑{/b}{/pen}买{pen=navy}{b}电击阴蒂棒{/b}{/pen}，结果他拿回来的是{/size}{/pen}"
    old "{pen=maroon}I mean, could I love someone like {pen=red}{b}[saga.cast.anon]{/b}{/pen}? I don't know...{/pen}{rt}{pen=maroon}maybe?{/pen}{/rt}"
    new "{pen=maroon}我是说，我会爱上像{pen=red}{b}[saga.cast.anon]{/b}{/pen}这样的人吗？我不知道……{/pen}{rt}{pen=maroon}也许？{/pen}{/rt}"
    old "{pen=maroon}{pen=orange}{size=-7}{b}STUPID [saga.cast.cedric!u]!{/b}{/size}{/pen}{space=30}{size=-5}He would have been perfect.{/size}{/pen}"
    new "{pen=maroon}{pen=orange}{size=-7}{b}[saga.cast.cedric!u]这个蠢货！{/b}{/size}{/pen}{space=30}{size=-5}他本来再合适不过了。{/size}{/pen}"
    old "{pen=purple}I guess he wanted to {pen=indigo}{b}FAP{/b}{/pen} to them or something{rb}...{/rb}{rt}so tragic{/rt}{space=35}{u}LOL{/u}!{/pen}"
    new "{pen=purple}我猜他想对着它们{pen=indigo}{b}打飞机{/b}{/pen}还是什么的{rb}……{/rb}{rt}太可悲了{/rt}{space=35}{u}哈哈哈{/u}！{/pen}"
    old "{pen=indigo}Ugh, {pen=black}{b}[saga.cast.anon]{/b}{/pen} is such an{/pen} {pen=navy}{size=-6}{b}{i}IDIOT!{/i}{/b}{/size}{/pen}{space=150}"
    new "{pen=indigo}呃，{pen=black}{b}[saga.cast.anon]{/b}{/pen}真是个{/pen}{pen=navy}{size=-6}{b}{i}白痴！{/i}{/b}{/size}{/pen}{space=150}"
    old "{pen=pink}toys{/pen} {pen=red}{size=-2}to play with for them. One with {pen=maroon}{b}{u}POWER{/u}{/b}{/pen} would be nice...{/size}{/pen}"
    new "{pen=pink}玩具{/pen}{pen=red}{size=-2}玩给他们看。要是{pen=maroon}{b}{u}够强力{/u}{/b}{/pen}就更好了……{/size}{/pen}"
    old "{rt}{size=+2}{pen=purple}{pen=aqua}existence{/pen} and her {pen=red}bleeding heart{/pen} just couldn't resist.{/pen}{/size}{/rt}{space=70}"
    new "{rt}{size=+2}{pen=purple}{pen=aqua}日子{/pen}，她一{pen=red}心软{/pen}就招架不住了。{/pen}{/size}{/rt}{space=70}"
    old "{pen=maroon}{size=-8}{b}WHY DOES HE HAVE TO HAVE {i}SUCH{/i} A {pen=pink}{size=+4}{b}{u}NICE{/u} COCK{/b}{/size}{/pen}?!{/b}{/size}{/pen}"
    new "{pen=maroon}{size=-8}{b}凭什么他偏偏有{i}那么{/i}一根{pen=pink}{size=+4}{b}{u}好用的{/u}鸡巴{/b}{/size}{/pen}？！{/b}{/size}{/pen}"
    old "{space=20}{pen=pink}{size=-3}Hopefully, this {pen=neonpink}{b}Sluttygram{/b}{/pen} thing pays out {pen=purple}{b}HUGE{/b}{/pen}...{/pen}"
    new "{space=20}{pen=pink}{size=-3}希望在{pen=neonpink}{b}Sluttygram{/b}{/pen}上能{pen=purple}{b}大赚一笔{/b}{/pen}……{/pen}"
    old "{size=+12}[saga.cast.ronald!u] PRESENTS:{/size}\nThe annual Summerville art contest!\n{vspace=40}{size=+2}FIRST PLACE CASH PRIZE!{/size}"
    new "{size=+12}[saga.cast.ronald!u]呈献：{/size}\n夏日镇年度艺术比赛！\n{vspace=40}{size=+2}一等奖现金奖励！{/size}"
    old "{pen=indigo}I had to {pen=neonpink}strip naked for {b}[saga.cast.anon]{/b}{/pen} to get that {pen=navy}stupid thing{/pen} too.{/pen}"
    new "{pen=indigo}为了拿到那个{pen=navy}蠢东西{/pen}，我也不得不{pen=neonpink}在{b}[saga.cast.anon]{/b}面前脱光{/pen}。{/pen}"
    old "{pen=pink}I should be an {pen=blue}{size=+10}actress{/size}{/pen} or a {pen=aqua}{size=+10}model{/size}{/pen} or something...{/pen}"
    new "{pen=pink}我应该做个{pen=blue}{size=+10}女演员{/size}{/pen}或者{pen=aqua}{size=+10}模特{/size}{/pen}之类的……{/pen}"
    old "{pen=purple}{b}UGH, WTF{/b}?!{/pen} {pen=maroon}{size=-2}When did I turn into such a {pen=black}fucking weirdo{/pen}?!{/size}{/pen}"
    new "{pen=purple}{b}呃，我靠{/b}？！{/pen} {pen=maroon}{size=-2}我什么时候变成了这么个{pen=black}他妈的怪胎{/pen}？！{/size}{/pen}"
    old "{pen=maroon}{size=-2}This is {pen=red}crazy{/pen}! Everybody is {pen=indigo}too chicken shit{/pen} to stream with me!{/size}{/pen}"
    new "{pen=maroon}{size=-2}这太{pen=red}疯狂了{/pen}！所有人都{pen=indigo}怂得要命{/pen}，不敢跟我一起直播！{/size}{/pen}"
    old "{rt}{pen=purple}{size=-1}Like seriously... {pen=red}{b}WTF?!{/b}{/pen} {pen=maroon}{b}BARF!{/b}{/pen}{/size}{/pen}{/rt}{space=200}"
    new "{rt}{pen=purple}{size=-1}说真的…… {pen=red}{b}搞什么鬼？！{/b}{/pen} {pen=maroon}{b}呕！{/b}{/pen}{/size}{/pen}{/rt}{space=200}"
    old "{pen=aqua}{size=-3}I made almost {pen=yellow}{size=-4}{b}THREE HUNDRED DOLLARS{/b}{/size}{/pen} in twenty minutes!!!{/size}{/pen}"
    new "{pen=aqua}{size=-3}我在二十分钟内赚了将近{pen=yellow}{size=-4}{b}三百美元{/b}{/size}{/pen}！！！{/size}{/pen}"
    old "{space=40}{pen=orange}.... but, like... why is {pen=maroon}{b}[saga.cast.anon]{/b}{/pen} bothering with {pen=red}her{/pen}?{/pen}"
    new "{space=40}{pen=orange}……但是，怎么说呢……为什么{pen=maroon}{b}[saga.cast.anon]{/b}{/pen}要费心搭理{pen=red}她{/pen}呢？{/pen}"
    old "{pen=orange}I bet he pictures me when he pla{rb}ys with himself...{/rb}{art}{pen=neonpink}Who wouldn't TBH? ;){/pen}{/art}{/pen}"
    new "{pen=orange}我敢打赌他自慰的时候脑海里全是我……{rb}{/rb}{art}{pen=neonpink}说实话，谁会不想呢？;){/pen}{/art}{/pen}"
    old "{pen=pink}{size=-2}How can someone with such a {pen=indigo}{size=+4}{b}huge cock{/b}{/size}{/pen} be such{/size}{/pen}{space=20}"
    new "{pen=pink}{size=-2}鸡巴长得那么{pen=indigo}{size=+4}{b}大{/b}{/size}{/pen}，怎么还能是{/size}{/pen}{space=20}"
    old "We're missing it! :( It's a full moon tonight, but I can't go anywhere in this state. Let's try again once the babies are born."
    new "我们错过了！:( 今晚是满月，但我这个状态哪儿也去不了。等宝宝出生后再试一次吧。"
    old "{pen=pink}{size=-3}The {pen=neonpink}{size=-3}HORNY SLUT{/size}{/pen} let it slip that she's been secretly filming{/size}{/pen}"
    new "{pen=pink}{size=-3}那个{pen=neonpink}{size=-3}饥渴荡妇{/size}{/pen}说漏嘴了，她一直在偷偷拍摄{/size}{/pen}"
    old "{pen=purple}You should see {pen=neonpink}{size=-2}{b}my new bikini!{/b}{/size}{/pen} It's sexy {pen=pink}{b}AF{/b}{/pen}!{/pen}"
    new "{pen=purple}你应该看看{pen=neonpink}{size=-2}{b}我的新比基尼！{/b}{/size}{/pen}简直性感{pen=pink}{b}得要命{/b}{/pen}！{/pen}"
    old "{pen=purple}{size=-4}More days like this and I'll spring for a{/size} {pen=lime}{size=-5}{b}BAD MONSTER{/b}{/size}{/pen}.{/pen}"
    new "{pen=purple}{size=-4}再这样过几天，我就要买那个{/size} {pen=lime}{size=-5}{b}坏怪物{/b}{/size}{/pen}了。{/pen}"
    old "{pen=aqua}{size=-3}I made sure I came all over {pen=indigo}{b}{i}{u}HIS{/u}{/i}{/b}{/pen} face this time! Hahaha!{/size}{/pen}"
    new "{pen=aqua}{size=-3}这次我可是喷得{pen=indigo}{b}{i}{u}他{/u}{/i}{/b}{/pen}满脸都是！哈哈哈！{/size}{/pen}"
    old "{pen=navy}I'm even starting to {pen=blue}think it's {size=+4}{i}cute{/i}{/size}{/pen}...{space=30}{size=+10}@.@;;{/size}{/pen}"
    new "{pen=navy}我甚至开始{pen=blue}觉得他这样还挺{size=+4}{i}可爱{/i}{/size}{/pen}……{space=30}{size=+10}@.@;;{/size}{/pen}"
    old "Sweetie, my contractions have started! I'm headed to the hospital now with [saga.cast.jenny], come find us when you get this."
    new "亲爱的，我开始宫缩了！我现在和[saga.cast.jenny]一起去医院，你收到消息后过来找我们。"
    old "{space=120}{pen=pink}I will {pen=silver}{b}{i}{u}LITERALLY{/u}{/i}{/b}{/pen} {pen=black}die of embarrassment! x_x{/pen}{/pen}"
    new "{space=120}{pen=pink}我会{pen=silver}{b}{i}{u}羞愤欲死{/u}{/i}{/b}{/pen}{pen=black}！x_x{/pen}{/pen}"
    old "We're missing it! :( It's a full moon tonight, but I can't go anywhere in this state. Let's try again once the baby is born."
    new "我们错过了！:( 今晚是满月，可我这样子哪儿也去不了。等宝宝出生后再试试吧。"
    old "{pen=blue}It was{/pen} {pen=purple}{b}SO{/b}{/pen} {pen=pink}{b}FUCKING{/b}{/pen} {pen=neonpink}{b}HAWT!{/b}{/pen}{space=40}"
    new "{pen=blue}太{/pen}{pen=purple}{b}他{/b}{/pen}{pen=pink}{b}妈{/b}{/pen}{pen=neonpink}{b}刺激了！{/b}{/pen}{space=40}"
    old "{pen=blue}{size=-2}The worst part is that now I'm stuck living with his {pen=red}{b}{u}LOSER{/u}{/b}{/pen} son!{/size}{/pen}"
    new "{pen=blue}{size=-2}最糟糕的是，我现在不得不和他那个{pen=red}{b}{u}废物{/u}{/b}{/pen}儿子住在一起！{/size}{/pen}"
    old "{pen=pink}spoil me, and when I needed... other things... {pen=neonpink}mm{size=+15}mmm{/size}{size=+25}m{/size}!{/pen}{/pen}"
    new "{pen=pink}宠我，在我需要……其他东西的时候……{pen=neonpink}嗯{size=+15}嗯嗯{/size}{size=+25}嗯{/size}！{/pen}{/pen}"
    old "{pen=pink}tell him I'm closing down shop for a while.{/pen}{space=75}{art}{pen=neonpink}How brilliant is that?!!{/pen}{/art}"
    new "{pen=pink}告诉他我要暂时关店了。{/pen}{space=75}{art}{pen=neonpink}多棒的主意啊？！{/pen}{/art}"
    old "{pen=purple}{size=-2}My regulars keep begging me to do anal stuff too... {pen=navy}{size=-6}{b}GROSS!{/b}{/pen}{/size}{/pen}"
    new "{pen=purple}{size=-2}我的常客们也一直求我走后门…… {pen=navy}{size=-6}{b}真恶心！{/b}{/pen}{/size}{/pen}"
    old "{pen=indigo}{size=-5}Soooooo I guess {/size}{/pen}{pen=silver}{size=+4}[saga.cast.anon]'s anxieties{/size}{/pen}{space=250}"
    new "{pen=indigo}{size=-5}所以啊，我猜{/size}{/pen}{pen=silver}{size=+4}[saga.cast.anon]的焦虑{/size}{/pen}{space=250}"
    old "{pen=maroon}{size=+1}Just had a HUGE fight with {pen=black}{b}[saga.cast.debbie]{/b}{/pen} about finding work!{/size}{/pen}"
    new "{pen=maroon}{size=+1}刚因为找工作的事和{pen=black}{b}[saga.cast.debbie]{/b}{/pen}大吵了一架！{/size}{/pen}"
    old "{pen=pink}anything I tell him to and {pen=neonpink}his cock is fucking {pen=indigo}{b}HUGE{/b}{/pen}{/pen}!{/pen}{space=20}"
    new "{pen=pink}他就做什么，而且{pen=neonpink}他的鸡巴真他妈{pen=indigo}{b}大{/b}{/pen}{/pen}！{/pen}{space=20}"
    old "{pen=pink}{size=-1}students {pen=neonpink}{size=+4}fucking{/size}{/pen} in the library and posting it online!{/size}{/pen}"
    new "{pen=pink}{size=-1}学生{pen=neonpink}{size=+4}在图书馆里乱搞{/size}{/pen}还发到了网上{/size}{/pen}！"
    old "{pen=purple}I should {pen=navy}NEVER{/pen} have broken up with {pen=black}{b}[saga.cast.cedric]{/b}{/pen}!{/pen}{space=40}"
    new "{pen=purple}我{pen=navy}绝对{/pen}不应该和{pen=black}{b}[saga.cast.cedric]{/b}{/pen}分手{/pen}{space=40}！"
    old "{pen=purple}{size=-3}At least {b}[saga.cast.debbie]{/b} says he'll be working for {b}Diane{/b} this summer...{/size}{/pen}"
    new "{pen=purple}{size=-3}至少{b}[saga.cast.debbie]{/b}说他今年夏天要为{b}Diane{/b}工作……{/size}{/pen}"
    old "{pen=red}{size=-1}I mean, I was worried about {pen=maroon}anal stuff{/pen} and the {pen=maroon}buttplug{/pen}{/size}{/pen}"
    new "{pen=red}{size=-1}我是说，之前我还担心{pen=maroon}玩后门{/pen}，可那根{pen=maroon}肛塞{/pen}{/size}{/pen}"
    old "{pen=silver}but it was {pen=aqua}{size=-6}{b}{i}SO{/i}{/b}{/size} much fun...{/pen} I got caught up in the moment...{/pen}"
    new "{pen=silver}但是那{pen=aqua}{size=-6}{b}{i}太{/i}{/b}{/size}有趣了……{/pen}我一时忘乎所以……{/pen}"
    old "{pen=indigo}{size=-1}That little {pen=purple}{b}{u}CREEPER{/u}{/b}{/pen} dared to sneak into my room today!{/size}{/pen}"
    new "{pen=indigo}{size=-1}那个小{pen=purple}{b}{u}混蛋{/u}{/b}{/pen}今天竟敢溜进我的房间！{/size}{/pen}"
    old "{pen=orange}{size=-1}I think I'll take it for a {pen=neonpink}test drive it tonight{/pen} before my stream.{/size}{/pen}"
    new "{pen=orange}{size=-1}我想今晚直播前{pen=neonpink}试用一下{/pen}。{/size}{/pen}"
    old "{pen=purple}{pen=indigo}{b}[saga.cast.anon]{/b}{/pen} and I had {pen=neonpink}sex{/pen} today on stream!{/pen}{space=70}"
    new "{pen=purple}{pen=indigo}{b}[saga.cast.anon]{/b}{/pen}今天和我在{pen=neonpink}直播里做爱了{/pen}！{/pen}{space=70}"
    old "{pen=aqua}{size=-3}I didn't even ask him to, which... ngl, is {pen=navy}definitely a little weird{/pen}...{/size}{/pen}"
    new "{pen=aqua}{size=-3}我甚至没让他这么做，这……说实话，{pen=navy}绝对有点奇怪{/pen}……{/size}{/pen}"
    old "{space=30}{pen=orange}I mean, my child really {pen=yellow}{size=+3}{i}{u}needs{/u}{/i}{/size}{/pen} me, you know?{/pen}"
    new "{space=30}{pen=orange}我的意思是，我的孩子真的{pen=yellow}{size=+3}{i}{u}需要{/u}{/i}{/size}{/pen}我，你明白吗？{/pen}"
    old "Hey sweetie...\nCan you please come \ndown and take the laundry\nbasket from my room\nto the basement?\n-[saga.cast.debbie]"
    new "亲爱的……\n能下来一趟，把\n我房间里的洗衣篮\n拿到地下室吗？\n-[saga.cast.debbie]"
    old "So tired. ~_~ It's a full moon tonight, but I can't keep my eyes open. Babies are a lot of work! Maybe next time... :("
    new "好累。~_~ 今晚是满月，但我眼睛都快睁不开了。宝宝太折腾人了！下次再说吧…… :("
    old "Sweetie, I really need to see you! There's something important I need to speak with you about. I'll be in the kitchen."
    new "亲爱的，我真的得见你！有件重要的事要跟你谈谈。我会在厨房等你。"
    old "{pen=pink}{size=-2}This had better not affect my {pen=aqua}{size=+4}camshow {u}profits{/u}{/size}{/pen}!!{/size}{/pen}"
    new "{pen=pink}{size=-2}这事最好别影响我的{pen=aqua}{size=+4}直播{u}收入{/u}{/size}{/pen}！！{/size}{/pen}"
    old "{pen=purple}{size=-4}Nothing crazy, just a little{/size} {pen=neonpink}strip tease and light masturbation{/pen}!{/pen}"
    new "{pen=purple}{size=-4}也没玩多疯，就是{/size} {pen=neonpink}跳了点脱衣舞，稍微自慰了一下{/pen}！{/pen}"
    old "{pen=maroon}{size=-4}Ugh, I've been {pen=red}{size=-2}wracking my brain{/size}{/pen} for days!{/size}{/pen}{space=80}"
    new "{pen=maroon}{size=-4}呃，我已经{pen=red}{size=-2}绞尽脑汁{/size}{/pen}好几天了！{/size}{/pen}{space=80}"
    old "{pen=neonpink}It hits all the {pen=indigo}right spots{/pen} and drives me {pen=purple}absolutely wild{/pen}...{/pen}"
    new "{pen=neonpink}每下都顶得{pen=indigo}恰到好处{/pen}，弄得我{pen=purple}快疯了{/pen}……{/pen}"
    old "{pen=pink}I mean, sure. He's a {pen=red}{size=-2}{u}doofus{/u}{/size}{/pen} but he'll pretty much do{/pen}{space=30}"
    new "{pen=pink}我是说，他是个{pen=red}{size=-2}{u}傻瓜{/u}{/size}{/pen}没错，但我让他做什么，{/pen}{space=30}"
    old "{space=85}{pen=maroon}{pen=red}{b}[saga.cast.anon]{/b}{/pen} continues to be a big hit with {pen=pink}my{/pen}{/pen}"
    new "{space=85}{pen=maroon}{pen=red}{b}[saga.cast.anon]{/b}{/pen}在{pen=pink}我的{/pen}{/pen}"
    old "So I may have accidentally told [saga.cast.eve] we could practice for the talent show with your karaoke machine. 😬🙏"
    new "所以我可能不小心告诉了[saga.cast.eve]我们可以用你的卡拉OK机为才艺表演练习。😬🙏"
    old "{pen=blue}That'd be {pen=navy}AWESOME{/pen}, I am {pen=pink}{size=-4}{b}SO FUCKING HORNY RN{/b}{/size}{/pen}!{/pen}"
    new "{pen=blue}那可就{pen=navy}太棒了{/pen}，我现在{pen=pink}{size=-4}{b}他妈的超饥渴{/b}{/size}{/pen}！{/pen}"
    old "{pen=pink}For years! She says it brings in {pen=indigo}{size=-5}{b}{u}FANTASTIC{/u}{/b}{/size}{/pen} money...{/pen}"
    new "{pen=pink}好多年了！她说这能赚{pen=indigo}{size=-5}{b}{u}大笔{/u}{/b}{/size}{/pen}的钱……{/pen}"
    old "{pen=pink}{size=+2}The police said his death was {pen=maroon}{size=+5}suspicious{/size}{/pen} but they{/size}{/pen}"
    new "{pen=pink}{size=+2}警方称他的死亡{pen=maroon}{size=+5}可疑{/size}{/pen}，但他们{/size}{/pen}"
    old "{pen=red}{size=-3}The viewer count {pen=pink}is growing everyday{/pen} and I need {/size}{pen=pink}more{/pen}{/pen}"
    new "{pen=red}{size=-3}观众数{pen=pink}每天在增长{/pen}，我需要{/size}{pen=pink}更多{/pen}{/pen}"
    old "{space=100}{pen=blue}for {pen=aqua}{b}two hundred dollars{/b}{/pen}!!!{/pen} {pen=yellow}{size=+10}$$${/size}{/pen}"
    new "{space=100}{pen=blue}就收了{pen=aqua}{b}两百美元{/b}{/pen}！！！{/pen} {pen=yellow}{size=+10}$$${/size}{/pen}"
    old "{pen=blue}I'm {pen=aqua}getting paid{/pen} to do it!!! {pen=yellow}{size=-5}LOLOLOLOL{/size}{/pen}{/pen}{space=80}"
    new "{pen=blue}我 {pen=aqua}拿钱{/pen} 做这事！！！ {pen=yellow}{size=-5}哈哈哈哈{/size}{/pen}{/pen}{space=80}"
    old "{pen=pink}didn't find any {size=+5}{pen=maroon}{u}evidence{/u}{/pen}{/size} that proved foul play.{/pen}{space=30}"
    new "{pen=pink}没有找到任何{size=+5}{pen=maroon}{u}证据{/u}{/pen}{/size}能证明他遭人谋害。{/pen}{space=30}"
    old "{pen=blue}He might be a {pen=navy}{size=-8}{b}{u}DISGUSTING{/u} {u}LOSER{/u}{/b}{/size}{/pen} but he's been{/pen}"
    new "{pen=blue}他虽然是个{pen=navy}{size=-8}{b}{u}恶心的{/u}{u}废柴{/u}{/b}{/size}{/pen}，可最近{/pen}"
    old "{pen=indigo}{size=-3}So I can't believe I'm saying this but,{/size}{/pen} {pen=neonpink}I love being a mom!{/pen}"
    new "{pen=indigo}{size=-3}真不敢相信我会这么说，但是，{/size}{/pen} {pen=neonpink}我超爱当妈妈！{/pen}"
    old "{pen=maroon}{size=-2}The weirdest part is that {pen=red}I never liked kids{/pen}... I was completely{/size}{/pen}"
    new "{pen=maroon}{size=-2}最奇怪的是{pen=red}我以前从来不喜欢小孩{/pen}……我完全{/size}{/pen}"
    old "{pen=indigo}{size=-3}I'm kind of {pen=navy}{b}having second thoughts{/b}{/pen} about all of this...{/size}{/pen}"
    new "{pen=indigo}{size=-3}不过这事我又有点{pen=navy}{b}犹豫{/b}{/pen}了……{/size}{/pen}"
    old "{pen=maroon}{pen=pink}fans{/pen}. They're {pen=neonpink}{b}begging me{/b}{/pen} to go further with him and{/pen}"
    new "{pen=maroon}{pen=pink}粉丝里{/pen}还是特别受欢迎。他们一直{pen=neonpink}{b}求我{/b}{/pen}和他更进一步，{/pen}"
    old "{pen=orange}If people will pay good money to watch random {pen=maroon}{size=-6}UGLY{/size}{/pen}{/pen}{space=20}"
    new "{pen=orange}随便找几个{pen=maroon}{size=-6}丑八怪，{/size}{/pen}{/pen}{space=20}"
    old "{pen=aqua}{size=-3}I guess it's back to the drawing board for ways to make {size=+10}money{/size}.{/size}{/pen}"
    new "{pen=aqua}{size=-3}我想我又得重新想办法赚{size=+10}钱{/size}了。{/size}{/pen}"
    old "{pen=blue}{size=+1}I mean, {u}who{/u} would want to pop that {pen=aqua}little dork cherry?!{/pen}{/size}{/pen}"
    new "{pen=blue}{size=+1}我是说，{u}谁会{/u}想给那个{pen=aqua}小呆子破处啊？！{/pen}{/size}{/pen}"
    old "{pen=orange}{size=-2}But {pen=red}screw it{/pen}, I don't care. I'm just happy I finally got one!{/size}{/pen}"
    new "{pen=orange}{size=-2}不过{pen=red}管他呢{/pen}，我不在乎。我就高兴终于也搞到了一个！{/size}{/pen}"
    old "{pen=purple}{size=-3}As long as he {pen=navy}keeps his mouth shut{/pen}{/size}, I think it could totally{/pen}"
    new "{pen=purple}{size=-3}只要他{pen=navy}闭上嘴{/pen}{/size}，我觉得这事就能{/pen}"
    old "{pen=red}{size=+2}{b}I FUCKING {u}HATE{/u}{/b}{/pen} {pen=blue}working.... {b}UGH!!{/b}{/size}{/pen}{space=30}"
    new "{pen=red}{size=+2}{b}我他妈最{u}讨厌{/u}{/b}{/pen}{pen=blue}工作了……{b}呃！！{/b}{/size}{/pen}{space=30}"
    old "{pen=silver}{size=-2}I swear I was just going to leave him with {pen=blue}{b}blue balls{/b}{/pen}{/size}{/pen}"
    new "{pen=silver}{size=-2}我发誓我本来只想让他{pen=blue}{b}欲火难耐{/b}{/pen}{/size}{/pen}"
    old "{pen=blue}That's more than I make in a week on {pen=orange}stupid{/pen} {pen=neonpink}Sluttygram{/pen}.{/pen}"
    new "{pen=blue}这比我一周在{pen=orange}那个破{/pen}{pen=neonpink}Sluttygram{/pen}上赚的钱还多。{/pen}"
    old "{pen=blue}{size=+2}pretty {pen=aqua}flush with {size=+5}cash{/size}{/pen} recently...{/size}{/pen}{space=100}"
    new "{pen=blue}{size=+2}手头倒挺{pen=aqua}宽{size=+5}裕{/size}{/pen}……{/size}{/pen}{space=100}"
    old "{pen=neonpink}All I can think about is how much {pen=silver}{size=+3}I wanna do it again{/size}{/pen}!!{/pen}"
    new "{pen=neonpink}我满脑子只想着{pen=silver}{size=+3}我有多想再来一次{/size}{/pen}！！{/pen}"
    old "{pen=orange}{size=-4}Not surprising really, he's been {pen=maroon}not very subtly{/pen} drooling{/size}{/pen}"
    new "{pen=orange}{size=-4}其实也不奇怪，他早就{pen=maroon}毫不掩饰地{/pen}对着{/size}{/pen}"
    old "{pen=pink}{size=-3}I always kinda assumed I'd have a {pen=silver}creepy stalker{/pen} one day...{/size}{/pen}"
    new "{pen=pink}{size=-3}我总觉得有一天会遇上{pen=silver}猥琐的跟踪狂{/pen}……{/size}{/pen}"
    old "{pen=silver}OMG! {pen=neonpink}That idiot{/pen} got me {pen=pink}{size=+3}{b}pregnant!{/b}{/pen}{/size}{/pen}"
    new "{pen=silver}天啊！{pen=neonpink}那个白痴{/pen}把我{pen=pink}{size=+3}{b}搞怀孕了！{/b}{/pen}{/size}{/pen}"
    old "{pen=indigo}It's gonna be {pen=silver}{size=+2}{i}really weird{/i}{/size}{/pen} doing things with him!{/pen}"
    new "{pen=indigo}要跟他做那些事，真是{pen=silver}{size=+2}{i}别扭{/i}{/size}{/pen}得要命！{/pen}"
    old "{pen=navy}Holy shit! {pen=blue}I'm getting {size=+5}{u}wet{/u}{/size}{/pen} just writing about this...{/pen}"
    new "{pen=navy}我操！{pen=blue}光是写这些我就{size=+5}{u}湿了{/u}{/size}{/pen}……{/pen}"
    old "{pen=purple}{size=-1}Even worse, I'm going to blow up like a {pen=blue}fucking whale{/pen} now!{/size}{/pen}"
    new "{pen=purple}{size=-1}更糟的是，我现在要像{pen=blue}该死的鲸鱼{/pen}一样膨胀起来了！{/size}{/pen}"
    old "{pen=silver}His {pen=neonpink}{b}huge cock{/b}{/pen} is turning me into a {pen=red}crazy person{/pen}!{/pen}"
    new "{pen=silver}他这根{pen=neonpink}{b}大鸡巴{/b}{/pen}简直快把我{pen=red}逼疯了{/pen}！{/pen}"
    old "{space=35}{pen=maroon}and they said I should {pen=orange}{size=+2}get a toy to play with{/size}{/pen}.{/pen}"
    new "{space=35}{pen=maroon}他们说我应该{pen=orange}{size=+2}买个玩具玩玩{/size}{/pen}。{/pen}"
    old "{pen=maroon}blindsided. I've heard the term {pen=pink}{size=+2}unconditional love{/size}{/pen} before{/pen}"
    new "{pen=maroon}没料到自己会这样。我以前听过{pen=pink}{size=+2}无条件的爱{/size}{/pen}这个词，{/pen}"
    old "{pen=orange}Things with {pen=yellow}{b}[saga.cast.anon]{/b}{/pen} are getting complicated.{/pen}{space=100}"
    new "{pen=orange}我和{pen=yellow}{b}[saga.cast.anon]{/b}{/pen}的关系越来越复杂了。{/pen}{space=100}"
    old "{pen=purple}{size=+10}{pen=blue}man up{/pen} and {pen=neonpink}{u}fuck{/u} me{/pen} on stream!{/size}{/pen}"
    new "{pen=purple}{size=+10}{pen=blue}像个男人一样{/pen}，{pen=neonpink}{u}在直播中操{/u}我{/pen}！{/size}{/pen}"
    old "{pen=silver}{size=+6}Still, it totally {pen=black}{size=-9}{b}CREEPED{/b}{/size}{/pen} me out!{/size}{/pen}"
    new "{pen=silver}{size=+6}不过，那可真{pen=black}{size=-9}{b}吓死{/b}{/size}{/pen}我了！{/size}{/pen}"
    old "{pen=silver}{size=-2}I don't understand why he's being such a {pen=pink}PUSSY{/pen} about it?!{/size}{/pen}"
    new "{pen=silver}{size=-2}我真不明白，他怎么这么{pen=pink}怂{/pen}？！{/size}{/pen}"
    old "{pen=aqua}Ugh, whatever. {pen=maroon}{size=-6}{b}SCREW HIM!{/b}{/size}{/pen} I'll find someone else.{/pen}"
    new "{pen=aqua}呃，管他呢。{pen=maroon}{size=-6}{b}去他的！{/b}{/size}{/pen}我再找别人。{/pen}"
    old "{pen=pink}HOLY SHIT!! {pen=neonpink}{size=+3}{b}Sluttygram{/b}{/size}{/pen} is such a waste of time!{/pen}"
    new "{pen=pink}天哪！！{pen=neonpink}{size=+3}{b}Sluttygram{/b}{/size}{/pen}真是太浪费时间了！{/pen}"
    old "{pen=blue}Just for taking my shirt off!{/pen}{space=20}{pen=navy}{size=-6}{b}{i}LOL!{/b}{/i}{/size}{/pen}"
    new "{pen=blue}不过就是脱了件上衣而已！{/pen}{space=20}{pen=navy}{size=-6}{b}{i}哈哈！{/b}{/i}{/size}{/pen}"
    old "{pen=maroon}I just need to trick {pen=black}{b}[saga.cast.anon]{/b}{/pen} into buying one for me...{/pen}"
    new "{pen=maroon}我只需要骗{pen=black}{b}[saga.cast.anon]{/b}{/pen}给我买一个……{/pen}"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] and request a footjob again after the date."
    new "在客厅看色情片被[saga.cast.debbie]抓住，然后在约会后再次要求足交。"
    old "{pen=pink}{pen=red}{b}[saga.cast.anon]{/b}{/pen} totally got a boner too. {i}Not surprising...{/i}{/pen}"
    new "{pen=pink}{pen=red}{b}[saga.cast.anon]{/b}{/pen}也硬起来了。{i}这有什么好奇怪的……{/i}{/pen}"
    old "{pen=purple}{size=+1}Okay so, I had the best idea, like {pen=pink}{b}EVER!!!!{/b}{/pen}!!!!{/size}{/pen}"
    new "{pen=purple}{size=+1}嗯，我有个超棒的主意，简直是{pen=pink}{b}有史以来最棒的！！！{/b}{/pen}！！！！{/size}{/pen}"
    old "{pen=silver}Am I {u}really{/u} considering this?! With {pen=indigo}{b}[saga.cast.anon]{/b}{/pen}?!{/pen}"
    new "{pen=silver}我{u}真的{/u}在考虑这个吗？！和{pen=indigo}{b}[saga.cast.anon]{/b}{/pen}？！{/pen}"
    old "{space=60}{pen=aqua}What {pen=indigo}{size=+8}the fuck{/size}{/pen} is going on in this household?{/pen}"
    new "{space=60}{pen=aqua}这家里{pen=indigo}{size=+8}他妈的{/size}{/pen}发生什么了？{/pen}"
    old "{pen=maroon}I know it's {pen=red}fucked up{/pen} but I can't say no to {pen=aqua}the money!{/pen}{/pen}"
    new "{pen=maroon}我知道这很{pen=red}操蛋{/pen}，但我没法拒绝{pen=aqua}这笔钱{/pen}！{/pen}"
    old "{pen=pink}anyone's dick before, but today I sucked {pen=indigo}{b}[saga.cast.anon]{/b}'s{/pen}...{/pen}"
    new "{pen=pink}给任何人口交过，今天却给了{pen=indigo}{b}[saga.cast.anon]{/b}{/pen}……{/pen}"
    old "{pen=aqua}My subs {pen=purple}{b}{u}TRIPLED{/u}{/b}{/pen} almost overnight, but it isn't enough.{/pen}"
    new "{pen=aqua}我的订阅量{pen=purple}{b}{u}几乎一夜之间涨到了原来的三倍{/u}{/b}{/pen}，但还不够。{/pen}"
    old "{pen=aqua}Ugh, {pen=lime}{b}[saga.cast.anon]{/b}{/pen} is relentless about this whole wanting me{/pen}"
    new "{pen=aqua}啊，{pen=lime}{b}[saga.cast.anon]{/b}{/pen}一直缠着我不放，非要我{/pen}"
    old "{pen=blue}It turns out he's some peon at the local movie theater.{/pen}{rt}{pen=purple}eww!{/pen}{/rt}"
    new "{pen=blue}原来他只是本地电影院的一个小职员。{/pen}{rt}{pen=purple}呃！{/pen}{/rt}"
    old "{pen=blue}{size=+2}So this morning I was messaging {b}[saga.cast.jane]{/b}, and{/size}{/pen}{space=70}"
    new "{pen=blue}{size=+2}今天早上我跟{b}[saga.cast.jane]{/b}发消息聊天，{/size}{/pen}{space=70}"
    old "{pen=blue}{size=+5}It's probably just his {pen=neonpink}{size=+5}{b}big dick{/b}{/size}{/pen}...{/pen}"
    new "{pen=blue}{size=+5}可能只是他那{pen=neonpink}{size=+5}{b}大鸡巴{/b}{/size}{/pen}……{/pen}"
    old "{pen=orange}It's so hard to describe how {pen=red}{size=+2}good{/size}{/pen} it makes me feel...{/pen}"
    new "{pen=orange}真是难以形容这让我感觉有多{pen=red}{size=+2}棒{/size}{/pen}……{/pen}"
    old "{pen=purple}First, I catch {pen=navy}{b}[saga.cast.anon]{/b}{/pen} spying on me in the shower...{/pen}"
    new "{pen=purple}首先，我抓到{pen=navy}{b}[saga.cast.anon]{/b}{/pen}在偷看我洗澡……{/pen}"
    old "{pen=blue}{size=+10}I mean, it is {pen=indigo}{size=-10}{b}{i}REALLY{/i}{/b}{/size}{/pen} nice!{/pen}"
    new "{pen=blue}{size=+10}我的意思是，这{pen=indigo}{size=-10}{b}{i}真的{/i}{/b}{/size}{/pen}很棒！{/pen}"
    old "{pen=pink}Chat {pen=yellow}{size=+4}didn't even notice{/size}{/pen} I was faking orgasms... LOL{/pen}"
    new "{pen=pink}直播间的观众{pen=yellow}{size=+4}根本没注意到{/size}{/pen}我在假装高潮……哈哈哈{/pen}"
    old "{pen=purple}{size=+4}I could make {pen=aqua}{u}SOOO{/u} much bank{/pen} if he would just{/size}{/pen}"
    new "{pen=purple}{size=+4}我能赚{pen=aqua}{u}超多{/u}钱{/pen}，只要他{/size}{/pen}"
    old "{pen=purple}{size=-3}Hopefully that means she'll get off my back about me losing my job.{/size}{/pen}"
    new "{pen=purple}{size=-3}希望这样她就不会再因为我丢了工作的事唠叨我了。{/size}{/pen}"
    old "{space=20}{pen=red}Like seriously, there {pen=maroon}isn't enough therapy in the world{/pen} to{/pen}"
    new "{space=20}{pen=red}说真的，这世上{pen=maroon}再多的心理治疗也没法{/pen}{/pen}"
    old "{pen=orange}Not because {pen=red}{size=-2}I want to{/size}{/pen} or anything but it'll be good{/pen}"
    new "{pen=orange}才不是{pen=red}{size=-2}我自己想这样{/size}{/pen}，只不过能当作{/pen}"
    old "{pen=pink}a {b}ginormous{/b} {pen=neonpink}{b}PUSSY?!{/b}{/pen} {size=-10}{b}LOLOL!{/b}{/size}{/pen}"
    new "{pen=pink}个{b}超级{/b}{pen=neonpink}{b}怂包？！{/b}{/pen}{size=-10}{b}哈哈哈哈！{/b}{/size}{/pen}"
    old "{pen=pink}{size=+4}I've been in school for like {pen=maroon}{u}4 years{/u}{/pen} now...{/size}{/pen}"
    new "{pen=pink}{size=+4}我已经在学校里待了差不多{pen=maroon}{u}4年{/u}{/pen}了……{/size}{/pen}"
    old "{pen=purple}I mean, I don't blame him. I'm like {pen=neonpink}{i}crazy{/i} {u}hot{/u}{/pen}...{/pen}"
    new "{pen=purple}我是说，我也不怪他。谁让我{pen=neonpink}{i}性感{/i}{u}得要命{/u}{/pen}呢……{/pen}"
    old "{pen=purple}{size=+3}Oh my God! I can't believe that {pen=black}FREAKING PERVERT{/pen}!{/size}{/pen}"
    new "{pen=purple}{size=+3}天哪！我真不敢相信那个{pen=black}该死的变态{/pen}！{/size}{/pen}"
    old "{pen=maroon}Can't we just be {pen=neonpink}fuck-buddies{/pen}? {i}What's wrong with that?{/i}{/pen}"
    new "{pen=maroon}我们就不能只当{pen=neonpink}炮友{/pen}吗？{i}这有什么问题吗？{/i}{/pen}"
    old "{pen=purple}His dick is {pen=neonpink}{size=-3}{b}{u}PERFECT{/u}{/b}{/size}{/pen}!{/pen}{space=120}"
    new "{pen=purple}他的鸡巴简直{pen=neonpink}{size=-3}{b}{u}完美无缺{/u}{/b}{/size}{/pen}！{/pen}{space=120}"
    old "{space=100}{pen=purple}{b}thrusting{/b}{/pen} {pen=indigo}deep{/pen} {pen=neonpink}inside me!{/pen}"
    new "{space=100}{pen=purple}{b}在我体内{/b}{/pen}{pen=indigo}深深地{/pen}{pen=neonpink}抽插！{/pen}"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] and request a footjob after the date."
    new "在客厅看色情片被[saga.cast.debbie]抓到，约会后要求足交。"
    old "Hey, are you free today? Something really important has come up and I need to speak with you ASAP."
    new "嘿，你今天有空吗？突然发生了件非常重要的事，我需要尽快和你谈谈。"
    old "{pen=indigo}And all that {pen=silver}{size=+35}{b}cum{/b}{/size}{/pen}... just...{/pen}{space=120}"
    new "{pen=indigo}还有那么多{pen=silver}{size=+35}{b}精液{/b}{/size}{/pen}……简直……{/pen}{space=120}"
    old "{pen=purple}OMG... I gave {pen=navy}{b}[saga.cast.anon]{/b}{/pen} a handjob on stream today!{/pen}"
    new "{pen=purple}天哪……我今天在直播时给{pen=navy}{b}[saga.cast.anon]{/b}{/pen}打手枪了！{/pen}"
    old "{space=100}{pen=maroon}{pen=orange}Crap!{/pen} {size=-4}He knows I'm enjoying this...{/size}{/pen}"
    new "{space=100}{pen=maroon}{pen=orange}糟糕！{/pen} {size=-4}他知道我很享受……{/size}{/pen}"
    old "{pen=aqua}{pen=yellow}{b}[saga.cast.anon]{/b}{/pen} managed to get free tickets off the guy{/pen}"
    new "{pen=aqua}{pen=yellow}{b}[saga.cast.anon]{/b}{/pen}设法从那人那里搞到了免费票{/pen}"
    old "{pen=black}{size=+3}The fans {pen=pink}absolutely loved{/pen} him! I don't get it...{/size}{/pen}"
    new "{pen=black}{size=+3}粉丝们{pen=pink}超喜欢{/pen}他！我真搞不懂……{/size}{/pen}"
    old "{pen=neonpink}My tits {i}are{/i} pretty {b}AWESOME{/b}{/pen} {pen=pink}after all.{/pen}{space=40}"
    new "{pen=neonpink}毕竟老娘这对奶子{i}可{/i}不是{b}盖的{/b}{/pen}{pen=pink}。{/pen}{space=40}"
    old "{pen=orange}practice for the {pen=neonpink}{size=+3}{b}camshows{/b}{/size}{/pen}.{/pen}{space=80}"
    new "{pen=orange}{pen=neonpink}{size=+3}{b}成人直播{/b}{/size}{/pen}前的练习。{/pen}{space=80}"
    old "{pen=purple}Does he have an {pen=silver}{size=+6}old lady fetish{/size}{/pen} or something?{/pen}"
    new "{pen=purple}他是不是有{pen=silver}{size=+6}恋老癖{/size}{/pen}还是什么？{/pen}"
    old "{space=80}{pen=red}turned out to be pretty {pen=yellow}fucking {b}{u}AWESOME{/u}{/b}{/pen}!{/pen}"
    new "{space=80}{pen=red}结果{pen=yellow}真他妈的{b}{u}太棒{/u}{/b}{/pen}了！{/pen}"
    old "Deprive [saga.cast.debbie] of attention, then catch her loading the dryer in the basement again."
    new "冷落[saga.cast.debbie]，再趁她在地下室往烘干机里装衣服时抓个正着。"
    old "{pen=blue}If {pen=navy}{b}[saga.cast.anon]{/b}{/pen} wants me to be his girlfriend so bad,{/pen}"
    new "{pen=blue}如果{pen=navy}{b}[saga.cast.anon]{/b}{/pen}那么想让我做他女朋友，{/pen}"
    old "{pen=blue}{pen=aqua}{b}[saga.cast.anon]{/b}{/pen} tracked down that creepy stalker for me.{/pen}"
    new "{pen=blue}{pen=aqua}{b}[saga.cast.anon]{/b}{/pen}帮我追踪到了那个诡异的跟踪狂。{/pen}"
    old "{pen=maroon}As if {pen=red}{b}{i}I{/i}{/b}{/pen} belong in grocery store or movie theater!{/pen}"
    new "{pen=maroon}好像{pen=red}{b}{i}我{/i}{/b}{/pen}该待在杂货店或电影院里似的！{/pen}"
    old "{space=45}{pen=indigo}Maybe this could be {pen=aqua}a whole {i}new{/i} angle{/pen} for me?{/pen}"
    new "{space=45}{pen=indigo}也许这可以成为{pen=aqua}我的全新{i}卖点{/i}{/pen}？{/pen}"
    old "{pen=maroon}Doesn't she realize {pen=pink}I'm {b}WAY{/b} too pretty{/pen} for that shit?!{/pen}"
    new "{pen=maroon}她难道不明白，就凭{pen=pink}我长得{b}这么{/b}漂亮{/pen}，哪能去干那种破活？！{/pen}"
    old "{pen=pink}Errmm... {pen=purple}{b}{u}OBVIOUSLY{/u}{i}!!!{/i}{/b}{/pen} That part's great!{/pen}"
    new "{pen=pink}呃……{pen=purple}{b}{u}当然想{/u}{i}！！！{/i}{/b}{/pen}这些当然好了！{/pen}"
    old "{pen=aqua}to be his girlfriend thing! It's {pen=navy}{size=-5}RIDICULOUS!!!{/size}{/pen}{/pen}"
    new "{pen=aqua}做他女朋友！太{pen=navy}{size=-5}荒谬了！！！{/size}{/pen}{/pen}"
    old "{pen=neonpink}I {size=+4}sucked his dick today{/size}!{/pen} {pen=pink}I've never sucked{/pen}"
    new "{pen=neonpink}今天我{size=+4}给他口交了{/size}！{/pen} {pen=pink}我以前可从没{/pen}"
    old "{pen=orange}over my {pen=neonpink}{size=+3}super hot{/size} bod{/pen} for a while now...{/pen}"
    new "{pen=orange}我这{pen=neonpink}{size=+3}火辣{/size}身材{/pen}流口水了……{/pen}"
    old "{pen=purple}We had some {pen=neonpink}naughty fun{/pen} in the theater too! ;D{/pen}{space=35}"
    new "{pen=purple}我们在电影院里也{pen=neonpink}玩了些刺激的{/pen}！;D{/pen}{space=35}"
    old "Hey, it's [saga.cast.grace]. I got your number from my sister. I need to speak with you ASAP."
    new "嘿，我是[saga.cast.grace]。我从我妹妹那里拿到了你的号码。我需要尽快和你谈谈。"
    old "Visit [saga.cast.tina] at home during her third trimester before [saga.cast.roxxy]'s contest."
    new "在[saga.cast.roxxy]比赛前，去她家看望[saga.cast.tina]，她现在正处于妊娠晚期。"
    old "{pen=blue}{pen=indigo}{b}[saga.cast.anon]{/b}{/pen} and I spied on the neighbors today,{/pen}"
    new "{pen=blue}{pen=indigo}{b}[saga.cast.anon]{/b}{/pen}和我今天偷窥了邻居，{/pen}"
    old "{pen=indigo}And can you {size=+4}{i}imagine{/i}{/size} if someone found out who he is?!{/pen}"
    new "{pen=indigo}你能{size=+4}{i}想象{/i}{/size}如果有人发现了他是谁吗？！{/pen}"
    old "{pen=orange}If this keeps up, I might actually be able to {pen=pink}buy{/pen}{/pen}{space=30}"
    new "{pen=orange}照这么赚下去，再过几个月我就{pen=pink}能{/pen}{/pen}{space=30}"
    old "{pen=orange}Well, {pen=yellow}{b}[saga.cast.anon]{/b}{/pen} agreed to stream with me...{/pen}"
    new "{pen=orange}嗯，{pen=yellow}{b}[saga.cast.anon]{/b}{/pen}同意和我一起直播了……{/pen}"
    old "{pen=pink}Not some {pen=maroon}chubby, neckbearded, stoner...{/pen} {pen=red}>:'({/pen}{/pen}"
    new "{pen=pink}不是某个{pen=maroon}胖乎乎、留络腮胡、抽大麻的……{/pen} {pen=red}>:'({/pen}{/pen}"
    old "{pen=orange}{size=+5}{pen=aqua}{b}The money{/b}{/pen} is really rolling in now!{/size}{/pen}"
    new "{pen=orange}{size=+5}{pen=aqua}{b}钱{/b}{/pen}现在真的滚滚而来！{/size}{/pen}"
    old "{pen=pink}It's not like my dating life has been {pen=purple}blowing up{/pen} lately...{/pen}"
    new "{pen=pink}也不是说我最近的{pen=purple}感情生活有多火热{/pen}……{/pen}"
    old "{pen=pink}Thank God I'm a such an {pen=purple}{b}amazing{/b}{/pen} actress!!{/pen}{space=30}"
    new "{pen=pink}谢天谢地，我真是个{pen=purple}{b}出色的{/b}{/pen}演员！！{/pen}{space=30}"
    old "{pen=purple}FUCKING STUPID {pen=silver}{b}[saga.cast.cedric!u]{/b}{/pen}!!!{/pen}{space=100}"
    new "{pen=purple}他妈的蠢货{pen=silver}{b}[saga.cast.cedric!u]{/b}{/pen}！！！{/pen}{space=100}"
    old "{pen=purple}She was going on about this website called {pen=neonpink}Sluttygram{/pen}.{/pen}"
    new "{pen=purple}她一直在唠叨一个叫{pen=neonpink}Sluttygram{/pen}的网站。{/pen}"
    old "Deprive [saga.cast.maria] of attention, then visit her apartment on Saturday evening again."
    new "先冷落[saga.cast.maria]，然后周六晚上再去她的公寓。"
    old "Help [saga.cast.maria] prepare pizzas after sex in the kitchen during her second trimester."
    new "在[saga.cast.maria]孕中期与她在厨房做爱后，帮她准备披萨。"
    old "Showtime, big fella! The moon is hitting its peak. See you in the graveyard at midnight! ;)"
    new "表演时间到了，大家伙！月亮正达到顶峰。午夜在墓地见！ ;)"
    old "The baby is coming, [saga.cast.anon]! [saga.cast.tina] is giving me a ride to the hospital."
    new "宝宝要出生了，[saga.cast.anon]！[saga.cast.tina]正送我去医院。"
    old "[saga.cast.jenny] went into labor, sweetie! Come find us at the hospital when you see this."
    new "[saga.cast.jenny]开始分娩了，亲爱的！看到这条消息就来医院找我们。"
    old "{pen=indigo}Oh well, at least I got another {pen=aqua}hundred bucks{/pen} out of him.{/pen}"
    new "{pen=indigo}哦，好吧，至少我从他那里又弄到了{pen=aqua}一百块{/pen}。{/pen}"
    old "{pen=indigo}because he was trying to steal my {pen=neonpink}naughty pictures{/pen}...{/pen}"
    new "{pen=indigo}因为他想偷我的{pen=neonpink}艳照{/pen}……{/pen}"
    old "{pen=pink}I'm so sick of being broke {i}{pen=purple}ALL THE TIME!{/pen}{/i}{/pen}{space=80}"
    new "{pen=pink}我真受够了{i}{pen=purple}老是穷得叮当响！{/pen}{/i}{/pen}{space=80}"
    old "Deprive [saga.cast.debbie] of attention, then catch her loading the dryer in the basement."
    new "冷落[saga.cast.debbie]，然后在地下室抓到她正在往烘干机里装衣服。"
    old "Have sex with [saga.cast.maria] in the pizzeria kitchen again during her second trimester."
    new "在她怀孕中期时，再次与[saga.cast.maria]在披萨店厨房做爱。"
    old "Help [saga.cast.maria] prepare pizzas after sex in the kitchen during her third trimester."
    new "在[saga.cast.maria]孕晚期与她在厨房做爱后，帮她准备披萨。"
    old "[saga.cast.grace] went into labor last night! [saga.cast.odette] took her to the hospital."
    new "[saga.cast.grace]昨晚临产了！[saga.cast.odette]送她去了医院。"
    old "[saga.cast.odette] went into labor last night! [saga.cast.grace] took her to the hospital."
    new "[saga.cast.odette]昨晚临产了！[saga.cast.grace]送她去了医院。"
    old "{pen=blue}So I used the {pen=navy}buttplug{/pen} today on stream for the first time.{/pen}"
    new "{pen=blue}所以我今天第一次在{pen=navy}直播中使用肛塞{/pen}。{/pen}"
    old "{pen=indigo}{size=-5}are getting worse because tonight I caught my{/size}{/pen}{space=100}"
    new "{pen=indigo}{size=-5}越来越糟了，因为今晚我发现我的{/size}{/pen}{space=100}"
    old "{pen=maroon}{size=-2}I asked the chat what they wanted to see me do next time{/size}{/pen}"
    new "{pen=maroon}{size=-2}我问直播间观众下次想看我做什么{/size}{/pen}"
    old "{pen=pink}{size=-3}Do I miss going out? Or having someone buy me nice things?{/size}{/pen}"
    new "{pen=pink}{size=-3}我想不想出去约会？想不想有人给我买好东西？{/size}{/pen}"
    old "{pen=purple}I signed up on {pen=neonpink}CAMslut{/pen} and did an actual show today.{/pen}"
    new "{pen=purple}我在{pen=neonpink}CAMslut{/pen}上注册了，今天做了一场真正的表演。{/pen}"
    old "{pen=purple}I thought it was gonna be {u}totally{/u} {u}gross{/u} and {u}awkward{/u}{/pen}"
    new "{pen=purple}我本以为这{u}绝对{/u}{u}恶心{/u}又{u}尴尬{/u}{/pen}"
    old "Deprive [saga.cast.debbie] of attention, then fool around with her in the basement again."
    new "冷落[saga.cast.debbie]，然后再和她在地下室亲热。"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] and request a footjob again."
    new "在客厅看色情片被[saga.cast.debbie]抓到，然后再要求一次足交。"
    old "Have sex with [saga.cast.maria] in the pizzeria kitchen again during her third trimester."
    new "在她怀孕晚期的时候，再次和[saga.cast.maria]在披萨店厨房做爱。"
    old "[saga.cast.anon]! The baby is coming! [saga.cast.grace] is taking me to the hospital now!"
    new "[saga.cast.anon]！宝宝要出生了！[saga.cast.grace]现在正带我去医院！"
    old "{pen=blue}Flicking my bean like a cavewoman is {i}super{/i} {pen=indigo}LAME!{/pen}{/pen}"
    new "{pen=blue}像个野女人一样自慰真是{i}超级{/i}{pen=indigo}逊！{/pen}{/pen}"
    old "{pen=blue}Turns out, {pen=navy}ANAL is fucking {pen=neonpink}AWESOME!{/pen}!{/pen}!{/pen}"
    new "{pen=blue}事实证明，{pen=navy}肛交真他妈{pen=neonpink}爽！{/pen}！{/pen}！{/pen}"
    old "{pen=maroon}{b}{u}ERASE{/u}{/b}{/pen}{pen=red} what I've just witnessed.{/pen}{space=220}"
    new "{pen=maroon}{b}{u}抹去{/u}{/b}{/pen}{pen=red}我刚才所目睹的一切。{/pen}{space=220}"
    old "{pen=orange}Why can't people just pay to see me being a {pen=red}sexy bitch?!{/pen}{/pen}"
    new "{pen=orange}我就当个{pen=red}性感婊子，让人付钱看，怎么就不行？！{/pen}{/pen}"
    old "{pen=pink}{size=-3}Now I get all the benefits of someone doting on me and if{/size}{/pen}"
    new "{pen=pink}{size=-3}这样既有人宠着，又能享尽好处；要是哪天{/size}{/pen}"
    old "Progress through [saga.cast.debbie]'s story during [saga.cast.jenny]'s second trimester."
    new "在[saga.cast.jenny]的孕中期推进[saga.cast.debbie]的剧情。"
    old "{pen=aqua}Talk about dreams coming true for the little {pen=navy}VIRGIN BOY!{/pen}{/pen}"
    new "{pen=aqua}这下那个{pen=navy}小处男{/pen}可真是梦想成真了！{/pen}"
    old "{pen=blue}I didn't get {pen=navy}a very good look{/pen} at him but I'm sure of it!{/pen}"
    new "{pen=blue}我没{pen=navy}看清{/pen}他，但我敢肯定有人在偷窥！{/pen}"
    old "{pen=pink}AND I'm still living here with these {pen=maroon}{u}losers{/u}{/pen}!!!!{/pen}"
    new "{pen=pink}而且我还和这些{pen=maroon}{u}废柴{/u}{/pen}一起住在这里！！！！{/pen}"
    old "{pen=pink}It takes {pen=purple}{u}FOREVER{/u}{/pen} to build up a subscriber base!{/pen}"
    new "{pen=pink}攒点订阅粉丝简直要等到{pen=purple}{u}天荒地老{/u}{/pen}！{/pen}"
    old "I need to speak with you urgently! It's about Daisy... Can you come see us at the barn?"
    new "我需要立刻和你谈谈！是关于Daisy的……你能来谷仓见我们吗？"
    old "Progress through [saga.cast.debbie]'s story during [saga.cast.jenny]'s third trimester."
    new "在[saga.cast.jenny]的孕晚期推进[saga.cast.debbie]的剧情。"
    old "{pen=aqua}I can't believe he's {pen=neonpink}been packing{/pen} this entire time!{/pen}"
    new "{pen=aqua}真不敢相信，他居然{pen=neonpink}一直藏着这么个大家伙{/pen}！{/pen}"
    old "{pen=blue}Okay, {pen=neonpink}CAMslut{/pen} is fucking {pen=indigo}AWESOME{/pen}!{/pen}"
    new "{pen=blue}好吧，{pen=neonpink}CAMslut{/pen}真他妈太{pen=indigo}棒{/pen}了！{/pen}"
    old "{pen=orange}{pen=neonpink}Sluttygram{/pen} sounded like such a perfect gig... :'({/pen}"
    new "{pen=orange}{pen=neonpink}Sluttygram{/pen}听起来是个超棒的差事……:'({/pen}"
    old "{pen=pink}{size=+2}I had him so well trained too... he totally knew how to{/size}{/pen}"
    new "{pen=pink}{size=+2}我把他训练得那么好……他完全知道怎么{/size}{/pen}"
    old "{pen=purple}I kinda... jerked him off... with my feet! {size=+30}x{/size}{b}D{/b}{/pen}"
    new "{pen=purple}我有点……用脚帮他……打飞机了！{size=+30}x{/size}{b}D{/b}{/pen}"
    old "[saga.cast.anon], the babies are coming! Taking [saga.cast.maria] to the hospital now!"
    new "[saga.cast.anon]，宝宝们要出生了！现在带[saga.cast.maria]去医院！"
    old "{pen=indigo}{b}[saga.cast.anon]{/b}{/pen} {pen=aqua}bought it for me.{/pen}{space=110}"
    new "{pen=indigo}{b}[saga.cast.anon]{/b}{/pen}{pen=aqua}给我买的。{/pen}{space=110}"
    old "{pen=orange}This could be a {pen=red}{i}game changer{/i}{/pen} for me!{/pen}{space=30}"
    new "{pen=orange}这对我来说可能是个{pen=red}{i}转折点{/i}{/pen}！{/pen}{space=30}"
    old "Deprive [saga.cast.maria] of attention, then visit her apartment on Saturday evening."
    new "先冷落[saga.cast.maria]，然后周六晚上去她的公寓。"
    old "Huge thank you to PyTom and the various other Ren'Py contributors! {=_hyperlink}♥{/=}"
    new "非常感谢PyTom和其他各位Ren'Py贡献者！ {=_hyperlink}♥{/=}"
    old "{pen=blue}{size=-2}totally enough for a camera.{/size} Maybe even a new vibe...{/pen}"
    new "{pen=blue}{size=-2}买相机绰绰有余。{/size}也许还能买根新振动棒……{/pen}"
    old "{pen=maroon}but I never really understood what it meant until I held {/pen}{space=10}"
    new "{pen=maroon}可我真正明白它的意思{/pen}，是在{space=10}"
    old "{color=d97c43}{outlinecolor=d97c43}WIN{/outlinecolor}{/color}\n{size=+20}BIGLY{/size}"
    new "{color=d97c43}{outlinecolor=d97c43}赢了{/outlinecolor}{/color}\n{size=+20}大获全胜{/size}"
    old "{pen=pink}I did finally come up with a {pen=maroon}last resort{/pen} though...{/pen}"
    new "{pen=pink}不过我终于想出了一个{pen=maroon}最后的办法{/pen}……{/pen}"
    old "Deprive [saga.cast.debbie] of attention, then fool around with her in the basement."
    new "先冷落[saga.cast.debbie]，再和她在地下室亲热。"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] and request a footjob."
    new "在客厅看色情片被[saga.cast.debbie]逮到，并要求足交。"
    old "[saga.cast.anon], the baby is coming! Taking [saga.cast.maria] to the hospital now!"
    new "[saga.cast.anon]，宝宝要出生了！我现在带[saga.cast.maria]去医院！"
    old "{pen=blue}My last show brought in almost {pen=aqua}a thousand dollars{/pen}!!{/pen}"
    new "{pen=blue}我上次直播赚了将近{pen=aqua}一千美元{/pen}！！{/pen}"
    old "{pen=maroon}Ugh, it's {pen=orange}{size=+10}sooo weird{/size}{/pen} though!!!{/pen}"
    new "{pen=maroon}呃，不过这{pen=orange}{size=+10}实在太奇怪了{/size}{/pen}！！！{/pen}"
    old "{pen=orange}on ex's always {pen=lime}repulsed me{/pen} but, like...{/pen}{space=90}"
    new "{pen=orange}前任口交，我都{pen=lime}嫌恶心{/pen}，可这次……{/pen}{space=90}"
    old "{pen=pink}I spoke with {pen=indigo}{b}[saga.cast.jane]{/b}{/pen} again today.{/pen}"
    new "{pen=pink}我今天又和{pen=indigo}{b}[saga.cast.jane]{/b}{/pen}说话了。{/pen}"
    old "{pen=pink}things get {pen=purple}{i}too real{/i}{/pen}, I can just{/pen}{space=120}"
    new "{pen=pink}开始{pen=purple}{i}动真感情{/i}{/pen}了，我就可以{/pen}{space=120}"
    old "{pen=silver}My fans are demanding {pen=neonpink}{size=+40}sex{/size}{/pen}...{/pen}"
    new "{pen=silver}粉丝们嚷着要看我{pen=neonpink}{size=+40}做爱{/size}{/pen}……{/pen}"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] again after the date."
    new "约会后又在客厅看色情片被[saga.cast.debbie]抓住。"
    old "I need to speak with you urgently! I think you did good work! Can you come see me?"
    new "我需要紧急和你谈谈！我觉得你做得不错！能来见我吗？"
    old "Visit [saga.cast.maria] in the kitchen of the pizzeria during her third trimester."
    new "在[saga.cast.maria]孕晚期去披萨店厨房找她。"
    old "[saga.cast.odette] is pregnant, again! I wonder if she used a donor this time too?"
    new "[saga.cast.odette]又怀孕了！不知道她这次是不是也用了捐精者？"
    old "{pen=blue}{size=-3}So I let the perv see my boobs today...{/size}{/pen}{space=100}"
    new "{pen=blue}{size=-3}所以我今天让那个变态看了我的乳房……{/size}{/pen}{space=100}"
    old "{pen=pink}Even after everything we've done, he's {i}still{/i} perving on me!{/pen}"
    new "{pen=pink}都已经做过那么多事了，他{i}还是{/i}色眯眯地盯着我！{/pen}"
    old "{pen=pink}You know what {pen=purple}{i}is{/i}{/pen} crazy though?!{/pen}{space=80}"
    new "{pen=pink}不过你知道真正{pen=purple}{i}离谱的{/i}{/pen}是什么吗？！{/pen}{space=80}"
    old "{pen=pink}{pen=neonpink}Sluttygram{/pen} might be worth looking into though.{/pen}"
    new "{pen=pink}{pen=neonpink}不过Sluttygram{/pen}或许值得研究一下。{/pen}"
    old "Catch [saga.cast.debbie] loading the dryer in the basement again before the date."
    new "约会前再看到[saga.cast.debbie]在地下室装烘干机。"
    old "{pen=blue}she said I could always come work with her at the {b}Library{/b}.{/pen}"
    new "{pen=blue}她说我随时可以去她工作的{b}图书馆{/b}上班。{/pen}"
    old "{pen=neonpink}{b}SUPER HOT?{/b}{/pen} {pen=pink}Like yours truly?{/pen}{space=40}"
    new "{pen=neonpink}{b}像本小姐这样的超级辣妹，{/b}{/pen}{pen=pink}他们会出多少钱？！{/pen}{space=40}"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] again post-boobjob."
    new "隆胸手术后，在客厅看黄片再次被[saga.cast.debbie]抓个正着。"
    old "{pen=aqua}and then {pen=lime}I punched him{/pen} right in his stupid face!{/pen}"
    new "{pen=aqua}然后{pen=lime}我一拳打{/pen}在他那张蠢脸上！{/pen}"
    old "{space=150}{pen=neonpink}Mmmmm{size=+15}mmmmmm{/size}{size=+25}mmm{/size}!{/pen}"
    new "{space=150}{pen=neonpink}唔唔唔{size=+15}唔唔唔唔{/size}{size=+25}唔唔{/size}！{/pen}"
    old "{space=70}{pen=blue}if things get {pen=navy}{u}desperate{/u}{/pen} enough.{/pen}"
    new "{space=70}{pen=blue}如果事情到了{pen=navy}{u}万不得已{/u}{/pen}的地步。{/pen}"
    old "Wait for [saga.cast.debbie] to visit Anon at night during her second trimester."
    new "等[saga.cast.debbie]在孕中期的夜晚来找你（Anon）。"
    old "Wait for [saga.cast.jenny] to visit at night again during her second trimester."
    new "等[saga.cast.jenny]在孕中期的夜晚再次来访。"
    old "Wait for [saga.cast.debbie] to visit Anon at night during her third trimester."
    new "等[saga.cast.debbie]在孕晚期的夜晚来找你（Anon）。"
    old "Wait for [saga.cast.jenny] to visit at night again during her third trimester."
    new "等[saga.cast.jenny]在孕晚期的夜晚再次来访。"
    old "[saga.cast.anon], the baby is coming! My dad is taking me to the hospital now!"
    new "[saga.cast.anon]，宝宝要出生了！我爸爸正带我去医院！"
    old "{pen=indigo}It really is {pen=navy}{size=-6}{b}GENIUS!!{/b}{/size}{/pen}{/pen}"
    new "{pen=indigo}这主意简直{pen=navy}{size=-6}{b}绝了！！{/b}{/size}{/pen}{/pen}"
    old "{pen=pink}At least my {pen=maroon}{u}EX{/u}{/pen} knew how to spoil meee{/pen}"
    new "{pen=pink}至少我的{pen=maroon}{u}前任{/u}{/pen}知道怎么宠我{/pen}"
    old "Ask [saga.cast.debbie] for a handjob in the shower once her story is complete"
    new "在她的故事完成后，向[saga.cast.debbie]要求在淋浴时帮你打手枪"
    old "{pen=indigo}While I was in the shower no less. Such an idiot.{/pen}{space=40}"
    new "{pen=indigo}偏偏还是在我洗澡的时候。真是个白痴。{/pen}{space=40}"
    old "{pen=maroon}Why am I {pen=pink}enjoying this so much{/pen}?!{/pen}{space=110}"
    new "{pen=maroon}为什么我{pen=pink}这么享受这个{/pen}？！{/pen}{space=110}"
    old "[saga.cast.daisy] gave birth last night. You should come and see the babies!"
    new "[saga.cast.daisy]昨晚生下了孩子。你应该来看看宝宝们！"
    old "{pen=indigo}{size=-7}{b}OMG!{/b}{/size} I totally did it!!!{/pen}{space=200}"
    new "{pen=indigo}{size=-7}{b}天啊！{/b}{/size}我完全做到了！！！{/pen}{space=200}"
    old "{pen=orange}I can't even begin to explain... The thought of going down{/pen}"
    new "{pen=orange}这事我根本说不清……以前光是想到要给{/pen}"
    old "{pen=pink}He should be {pen=indigo}on his knees{/pen} thanking me ffs.{/pen}"
    new "{pen=pink}他应该{pen=indigo}跪下来{/pen}感谢我，我靠。{/pen}"
    old "{space=150}{pen=neonpink}my {b}KITTY{/b} is going {b}{u}CRAZY{/u}!{/b}{/pen}"
    new "{space=150}{pen=neonpink}我的{b}小穴{/b}都快憋{b}{u}疯了{/u}！{/b}{/pen}"
    old "{pen=aqua}The {pen=lime}FREAKS{/pen} absolutely ate it up!{/pen}{space=100}"
    new "{pen=aqua}那些{pen=lime}变态{/pen}完全被迷住了！{/pen}{space=100}"
    old "{pen=blue}I bet I could find ways to get more out of him...{/pen}{space=40}"
    new "{pen=blue}我肯定能想办法再从他身上榨些钱……{/pen}{space=40}"
    old "{pen=pink}{size=+10}I am {pen=maroon}{u}SOOO{/u}{/pen} bored!!{/size}{/pen}"
    new "{pen=pink}{size=+10}我{pen=maroon}{u}超级{/u}{/pen}无聊！！{/size}{/pen}"
    old "{pen=purple}I usually get so mad when he pulls this shit but I dunno,{/pen}"
    new "{pen=purple}换作平时，他敢这样我早就发火了，可这次也不知道怎么回事，{/pen}"
    old "All good, dude. Got a raid scheduled, but you can always start without me."
    new "没事，哥们。我有一个突袭计划，不过你可以不等我先开始。"
    old "Get caught watching porn in the lounge by [saga.cast.jenny], and have sex."
    new "在客厅看黄片被[saga.cast.jenny]抓到，然后做爱。"
    old "Go shopping with [saga.cast.debbie] after getting a blowjob in the shower."
    new "在淋浴时口交后和[saga.cast.debbie]去购物。"
    old "Go shopping with [saga.cast.debbie] after getting a handjob in the shower."
    new "在淋浴时被手淫后，和[saga.cast.debbie]一起去购物。"
    old "[saga.cast.daisy] gave birth last night. You should come and see the baby!"
    new "[saga.cast.daisy]昨晚生下了孩子。你应该过来看看宝宝！"
    old "{pen=indigo}He must have realised he'll be a pathetic virgin forever{/pen}"
    new "{pen=indigo}他一定意识到自己将永远是可悲的处男{/pen}"
    old "{pen=orange}{pen=pink}my own place{/pen} in a few months!{/pen}{space=130}"
    new "{pen=orange}{pen=pink}买套自己的房子了{/pen}！{/pen}{space=130}"
    old "{pen=blue}{size=+2}I just hope I don't have to get a job....{/size}{/pen}"
    new "{pen=blue}{size=+2}我只希望我不必去工作……{/size}{/pen}"
    old "{space=80}{pen=aqua}I'm not going to lie, I think about it a lot...{/pen}"
    new "{space=80}{pen=aqua}老实说，我经常在想这件事…{/pen}"
    old "Fool around with [saga.cast.debbie] in the kitchen in the evening again."
    new "晚上再次在厨房和[saga.cast.debbie]亲热。"
    old "[saga.cast.anon], the baby is coming! I'm on my way to the hospital now!"
    new "[saga.cast.anon]，宝宝要出生了！我正赶去医院！"
    old "{pen=indigo}He kinda weirds me out now... when I see him all I can{/pen}"
    new "{pen=indigo}他现在让我有点不自在……每次看到他，{/pen}"
    old "{pen=pink}or {pen=navy}peer pressure{/pen} from all my fans but...{/pen}"
    new "{pen=pink}或者说是{pen=navy}顶不住粉丝们的压力{/pen}，可……{/pen}"
    old "{space=135}{pen=blue}he can {pen=aqua}pay for the privilege{/pen}.{/pen}"
    new "{space=135}{pen=blue}那就让他{pen=aqua}掏钱买这个资格{/pen}。{/pen}"
    old "Peek at [saga.cast.debbie] in the bathroom during her second trimester."
    new "在孕中期偷看[saga.cast.debbie]在浴室里。"
    old "Progress through [saga.cast.jenny]'s story during her second trimester."
    new "在[saga.cast.jenny]孕中期推进她的剧情。"
    old "Progress through [saga.cast.maria]'s story during her second trimester."
    new "在[saga.cast.maria]孕中期推进她的剧情。"
    old "{pen=blue}I did manage to blackmail some money out of him though,{/pen}"
    new "{pen=blue}不过我确实从他那里勒索到了一些钱，{/pen}"
    old "{pen=orange}people fuck, just imagine what they would pay someone{/pen}"
    new "{pen=orange}上个床都有人肯花大钱看，那要是换成{/pen}"
    old "Peek at [saga.cast.debbie] in the bathroom during her third trimester."
    new "在[saga.cast.debbie]孕晚期偷看她在浴室里。"
    old "Progress through [saga.cast.jenny]'s story during her third trimester."
    new "在[saga.cast.jenny]孕晚期推进她的剧情。"
    old "Progress through [saga.cast.maria]'s story during her third trimester."
    new "在[saga.cast.maria]孕晚期推进她的剧情。"
    old "{pen=aqua}This is exactly what I've been looking for!{/pen}{space=100}"
    new "{pen=aqua}这正是我一直在找的！{/pen}{space=100}"
    old "Fool around with [saga.cast.jenny] in her bedroom again and deny her."
    new "再次在[saga.cast.jenny]的卧室里和她亲热，然后拒绝她。"
    old "Peek at [saga.cast.debbie] in the shower during her second trimester."
    new "在[saga.cast.debbie]孕中期偷看她洗澡。"
    old "Progress through [saga.cast.melody]'s story, and win the talent show."
    new "推进[saga.cast.melody]的剧情，并赢得才艺表演。"
    old "{pen=orange}I'm thinking we should make this a regular thing...{/pen}"
    new "{pen=orange}我在想，以后是不是该经常这样……{/pen}"
    old "{pen=pink}God, I hope nobody finds out about this...{/pen}{space=120}"
    new "{pen=pink}天啊，我希望没人发现这件事……{/pen}{space=120}"
    old "{pen=purple}And now, he's even peeping on me {i}in my room!{/i}{/pen}"
    new "{pen=purple}现在，他甚至在我房间里偷看我{i}！{/i}{/pen}"
    old "{pen=purple}Apparently people pay girls to post pictures there,{/pen}"
    new "{pen=purple}听说女孩们在那儿发照片，就有人愿意付钱，{/pen}"
    old "Fool around [saga.cast.melody] in her office, and ask for a blowjob."
    new "在[saga.cast.melody]办公室里与她亲热，然后要求口交。"
    old "Peek at [saga.cast.debbie] in the bathroom midway through her story."
    new "在[saga.cast.debbie]的剧情中段，去浴室偷看她。"
    old "Peek at [saga.cast.debbie] in the shower during her third trimester."
    new "在[saga.cast.debbie]孕晚期偷看她洗澡。"
    old "Agree to pay [saga.cast.jenny] for the girlfriend experience again."
    new "同意再次付钱给[saga.cast.jenny]获取女友体验。"
    old "Get caught watching porn in the lounge by [saga.cast.debbie] again."
    new "再次在客厅看色情片被[saga.cast.debbie]抓到。"
    old "Peek at [saga.cast.jenny] in the shower after giving her a sex toy."
    new "给她一个性玩具后偷看[saga.cast.jenny]洗澡。"
    old "Wait for [saga.cast.debbie] to visit Anon at night before the date."
    new "约会前，等[saga.cast.debbie]晚上来找你。"
    old "{space=225}{pen=neonpink}{b}I think I {u}might{/u} do it.{/b}{/pen}"
    new "{space=225}{pen=neonpink}{b}我想我{u}可能{/u}会这么做。{/b}{/pen}"
    old "Fool around with [saga.cast.debbie] in the kitchen in the evening."
    new "晚上在厨房和[saga.cast.debbie]亲热。"
    old "Participate in another baby-making session with [saga.cast.maria]."
    new "再和[saga.cast.maria]来一次造人活动。"
    old "Peek at [saga.cast.debbie] in the shower midway through her story."
    new "在[saga.cast.debbie]的剧情中段，偷看她洗澡。"
    old "Suggest a camshow to [saga.cast.jenny] when she's not in the mood."
    new "在[saga.cast.jenny]没心情时向她提议做直播。"
    old "Wait for [saga.cast.debbie] to visit Anon at night after the date."
    new "约会后，等[saga.cast.debbie]晚上来找你。"
    old "[saga.cast.anon] is {dom=assertive}, and denies [saga.cast.jenny]."
    new "[saga.cast.anon]采取{dom=强势}态度，拒绝了[saga.cast.jenny]。"
    old "{pen=pink}Like, who cares what the viewers think?!{/pen}{space=80}"
    new "{pen=pink}拜托，谁在乎观众怎么想？！{/pen}{space=80}"
    old "{pen=purple}I can't even begin to describe how good it felt!{/pen}"
    new "{pen=purple}我简直无法形容那感觉有多棒！{/pen}"
    old "Fool around with [saga.cast.tina] in the lobby of the bank again."
    new "再次在银行大厅和[saga.cast.tina]亲热。"
    old "Peek at [saga.cast.jenny] in the shower again early in her story."
    new "在[saga.cast.jenny]的剧情前期，再次偷看她洗澡。"
    old "Tell [saga.cast.judith] to meet you in the girl's bathroom again."
    new "再次告诉[saga.cast.judith]在女厕所见面。"
    old "{pen=indigo}Then she straight up chased me back to my room,{/pen}"
    new "{pen=indigo}然后她直接把我追回了我的房间，{/pen}"
    old "{pen=pink}I need to break out some of my toys...{/pen}{space=100}"
    new "{pen=pink}我需要拿出一些玩具……{/pen}{space=100}"
    old "Ask [saga.cast.debbie] for a blowjob while she is in the shower."
    new "在[saga.cast.debbie]洗澡时要求她口交。"
    old "Fool around with [saga.cast.maria] in the pizzeria pantry again."
    new "再次在披萨店储藏室与[saga.cast.maria]亲热。"
    old "Just had the baby. We're at the hospital if you'd like to visit."
    new "刚生下孩子。想来看望的话，我们在医院。"
    old "Mom went into labor. The security guys took her to the hospital."
    new "妈妈开始分娩了，保安人员把她送去了医院。"
    old "Peek at [saga.cast.jenny] in the shower during second trimester."
    new "在[saga.cast.jenny]孕中期偷看她洗澡。"
    old "Use [saga.cast.debbie]'s panties again midway through her story."
    new "在[saga.cast.debbie]的剧情中段，再次使用她的内裤。"
    old "Use the peephole in the attic in the evening early in her story."
    new "在她的剧情前期，傍晚时使用阁楼上的窥视孔。"
    old "{pen=orange}I don't wanna be tied down though...{/pen}{space=85}"
    new "{pen=orange}但我不想被束缚……{/pen}{space=85}"
    old "{pen=pink}It's even more depressing now that I'm single...{/pen}"
    new "{pen=pink}现在单身了，更让人沮丧……{/pen}"
    old "{space=85}{pen=aqua}It was {pen=blue}{u}perfect{/u}{/pen}!{/pen}"
    new "{space=85}{pen=aqua}这真是{pen=blue}{u}完美{/u}{/pen}！{/pen}"
    old "Have sex with [saga.cast.debbie] in the kitchen in the morning."
    new "早上在厨房与[saga.cast.debbie]发生关系。"
    old "Have sex with [saga.cast.tina] in her living room {i}again{/i}."
    new "与[saga.cast.tina]在客厅里{i}再次{/i}做爱。"
    old "Help [saga.cast.maria] prepare pizzas after sex in the kitchen."
    new "在厨房做爱后，帮[saga.cast.maria]准备披萨。"
    old "Interact with sleeping [saga.cast.tony] in his apartment again."
    new "再次在他公寓里与睡着的[saga.cast.tony]互动。"
    old "Peek at [saga.cast.jenny] in the shower during third trimester."
    new "在[saga.cast.jenny]孕晚期偷看她洗澡。"
    old "Use the peephole in the attic in the evening late in her story."
    new "在她的剧情后期，傍晚时使用阁楼上的窥视孔。"
    old "{i}[saga.cast.diane]'s story will return in future updates.{/i}"
    new "{i}[saga.cast.diane]的故事将在未来的更新中回归。{/i}"
    old "{i}[saga.cast.josie]'s story will return in future updates.{/i}"
    new "{i}[saga.cast.josie]的故事将在未来的更新中回归。{/i}"
    old "{pen=blue}Somebody has been spying on me out by our pool!{/pen}"
    new "{pen=blue}有人一直在我们的游泳池旁偷窥我！{/pen}"
    old "Have sex with [saga.cast.maria] in the pizzeria kitchen again."
    new "再次在披萨店厨房与[saga.cast.maria]做爱。"
    old "Peek at [saga.cast.debbie] in the bathroom early in her story."
    new "在[saga.cast.debbie]的剧情前期，去浴室偷看她。"
    old "Peek at [saga.cast.jenny] in the shower after blowjob camshow."
    new "口交直播后，在淋浴时偷看[saga.cast.jenny]。"
    old "Progress {sub=submissively} through [saga.cast.jenny]'s story."
    new "沿{sub=顺从}路线推进[saga.cast.jenny]的剧情。"
    old "{pen=red}I'm sure it will be fine... maybe...{/pen}{space=100}"
    new "{pen=red}我敢肯定会没事的……大概……{/pen}{space=100}"
    old "{pen=silver}I mean, what good would it do me?{/pen}{space=100}"
    new "{pen=silver}我是说，这对我有什么好处呢？{/pen}{space=100}"
    old "Agree to pay [saga.cast.jenny] for the girlfriend experience."
    new "同意向[saga.cast.jenny]支付女友体验的费用。"
    old "Get caught watching porn in the lounge by [saga.cast.debbie]."
    new "在客厅看色情片被[saga.cast.debbie]发现了。"
    old "Just had twins. We're at the hospital if you'd like to visit."
    new "刚生了双胞胎。想来看望的话，我们在医院。"
    old "Let [saga.cast.tony] jerk off, then later suggest a threeway."
    new "让[saga.cast.tony]打飞机，之后再提议三人行。"
    old "Peek into the backroom of Pink after grabbing the Electoclit."
    new "拿到电子阴蒂后，窥视一下粉色诱惑的后屋。"
    old "Progress {dom=assertively} through [saga.cast.jenny]'s story."
    new "沿{dom=强势}路线推进[saga.cast.jenny]的剧情。"
    old "Push further when spending the night with [saga.cast.debbie]."
    new "与[saga.cast.debbie]过夜时更进一步。"
    old "{pen=blue}And you know the best part about all of this?{/pen}"
    new "{pen=blue}你知道这一切最棒的部分是什么吗？{/pen}"
    old "Climb into bed with [saga.cast.jenny] at night and deny her."
    new "晚上和[saga.cast.jenny]一起上床，并拒绝她。"
    old "Get caught watching porn in the lounge by [saga.cast.jenny]."
    new "在客厅看色情片被[saga.cast.jenny]发现。"
    old "Make a mess when spending the night with [saga.cast.debbie]."
    new "和[saga.cast.debbie]过夜时把房间弄得一团糟。"
    old "Peek at [saga.cast.debbie] in the shower early in her story."
    new "在[saga.cast.debbie]的剧情前期，偷看她洗澡。"
    old "Reach lower when spending the night with [saga.cast.debbie]."
    new "和[saga.cast.debbie]过夜时把手往下伸。"
    old "Catch [saga.cast.debbie] loading the dryer in the basement."
    new "在地下室撞见[saga.cast.debbie]在往烘干机里放衣服。"
    old "Don't stop when spending the night with [saga.cast.debbie]."
    new "和[saga.cast.debbie]过夜时不要停下来。"
    old "Fool around with [saga.cast.tina] in the lobby of the bank."
    new "在银行大厅与[saga.cast.tina]亲热。"
    old "Keep going when spending the night with [saga.cast.debbie]."
    new "与[saga.cast.debbie]共度夜晚时继续下去。"
    old "Kiss lower when spending the night with [saga.cast.debbie]."
    new "与[saga.cast.debbie]共度夜晚时向下亲吻。"
    old "Progress through main story, and let [saga.cast.tony] stay."
    new "推进主线剧情，并让[saga.cast.tony]留下来。"
    old "Tell [saga.cast.judith] to meet you in the girl's bathroom."
    new "告诉[saga.cast.judith]在女厕所见面。"
    old "Use the telescope to peek into Tammy's room in the morning."
    new "早上用望远镜偷看Tammy的房间。"
    old "{pen=maroon}God! I haven't had sex in like, MONTHS...{/pen}"
    new "{pen=maroon}天哪！我都好几个月没做爱了……{/pen}"
    old "Enter the bathroom while [saga.cast.debbie] is drying off."
    new "当[saga.cast.debbie]正在擦干身体时进入浴室。"
    old "Fool around with [saga.cast.debbie] in the basement again."
    new "再次在地下室和[saga.cast.debbie]亲热。"
    old "Fool around with [saga.cast.jenny] during breakfast again."
    new "再次在早餐时和[saga.cast.jenny]亲热。"
    old "Fool around with [saga.cast.jenny] during breakfast. {dom}"
    new "在早餐时和[saga.cast.jenny]亲热。{dom}"
    old "Fool around with [saga.cast.jenny] during breakfast. {sub}"
    new "在早餐时和[saga.cast.jenny]亲热。{sub}"
    old "Fool around with [saga.cast.maria] in the pizzeria pantry."
    new "在比萨店储藏室和[saga.cast.maria]亲热。"
    old "Have lapdance with [saga.cast.melody] in her office again."
    new "再次在她的办公室和[saga.cast.melody]进行膝上舞。"
    old "{pen=blue}then he ate me out in his room.{/pen}{space=100}"
    new "{pen=blue}然后他在他的房间里给我口交了。{/pen}{space=100}"
    old "{pen=pink}It's not even making me that much money...{/pen}"
    new "{pen=pink}结果也没赚着几个钱……{/pen}"
    old "Ask [saga.cast.debbie] for another handjob in the shower."
    new "请求[saga.cast.debbie]在淋浴时再给你打一次手枪。"
    old "Engage in foreplay with [saga.cast.debbie] in the shower."
    new "在淋浴时与[saga.cast.debbie]进行前戏。"
    old "Fool around with [saga.cast.jenny] in the backyard. {dom}"
    new "在后院与[saga.cast.jenny]亲热。{dom}"
    old "Fool around with [saga.cast.jenny] in the backyard. {sub}"
    new "在后院与[saga.cast.jenny]亲热。{sub}"
    old "Fool around with [saga.cast.tony] in his apartment again."
    new "再次在他的公寓里与[saga.cast.tony]亲热。"
    old "Have sex when spending the night with [saga.cast.debbie]."
    new "与[saga.cast.debbie]共度夜晚时发生性关系。"
    old "Impregnate [saga.cast.jenny] and wait for her invitation."
    new "让[saga.cast.jenny]怀孕并等待她的邀请。"
    old "Interact with sleeping [saga.cast.tony] in his apartment."
    new "在他的公寓里与睡着的[saga.cast.tony]互动。"
    old "Join [saga.cast.jenny] in the shower for a blowjob again."
    new "再次加入[saga.cast.jenny]的淋浴来一次口交。"
    old "Use the peephole in the attic after the pregnant camshow."
    new "在孕妇直播后使用阁楼的窥视孔。"
    old "Use the telescope to peek into Mia's room in the evening."
    new "晚上用望远镜偷看Mia的房间。"
    old "Use the telescope to peek into Mia's room in the morning."
    new "早上用望远镜偷看Mia的房间。"
    old "{space=100}{pen=purple}work! I'll ask him tomorrow.{/pen}"
    new "{space=100}{pen=purple}成！我明天问问他。{/pen}"
    old "Fool around with [saga.cast.jenny] in her bedroom again."
    new "再次在[saga.cast.jenny]的卧室里和她亲热。"
    old "Have sex with [saga.cast.tina] in her living room again."
    new "再次在[saga.cast.tina]的客厅里和她做爱。"
    old "{pen=pink}I bet they'd pay top dollar for my pics!{/pen}"
    new "{pen=pink}我敢打赌他们会为我的照片花大价钱！{/pen}"
    old "Put on another pregnant camshow with [saga.cast.jenny]."
    new "和[saga.cast.jenny]再办一场怀孕主题直播。"
    old "Grind when spending the night with [saga.cast.debbie]."
    new "与[saga.cast.debbie]过夜时相互磨蹭。"
    old "Put on another blowjob camshow with [saga.cast.jenny]."
    new "和[saga.cast.jenny]再开一场口交直播。"
    old "Put on another handjob camshow with [saga.cast.jenny]."
    new "和[saga.cast.jenny]再开一场手交直播。"
    old "Use [saga.cast.debbie]'s panties again after the date."
    new "约会后再次使用[saga.cast.debbie]的内裤。"
    old "Warm [saga.cast.debbie] up in the shower post-boobjob."
    new "在淋浴时给[saga.cast.debbie]暖暖身子，并进行乳交。"
    old "Catch [saga.cast.debbie] taking a break in the lobby."
    new "撞见[saga.cast.debbie]在大厅休息。"
    old "Climb into bed with [saga.cast.jenny] at night. {dom}"
    new "晚上爬上床和[saga.cast.jenny]一起。{dom}"
    old "Climb into bed with [saga.cast.jenny] at night. {sub}"
    new "晚上爬上床和[saga.cast.jenny]一起。{sub}"
    old "Have sex with [saga.cast.melody] in her office again."
    new "再次在她的办公室与[saga.cast.melody]做爱。"
    old "Use the telescope to peek into Tammy's room at night."
    new "晚上用望远镜偷窥Tammy的房间。"
    old "Ask [saga.cast.judith] to go faster in the bathroom."
    new "在浴室里让[saga.cast.judith]快点。"
    old "Fool around with [saga.cast.debbie] in the backyard."
    new "在后院与[saga.cast.debbie]亲热。"
    old "Fool around with [saga.cast.debbie] in the basement."
    new "在地下室与[saga.cast.debbie]亲热。"
    old "Have sex with [saga.cast.jenny] in the shower. {dom}"
    new "在浴室与[saga.cast.jenny]做爱。{dom}"
    old "Have sex with [saga.cast.jenny] in the shower. {sub}"
    new "在浴室与[saga.cast.jenny]做爱。{sub}"
    old "{i}The main story will return in future updates.{/i}"
    new "{i}主线故事将在后续更新中回归。{/i}"
    old "{pen=pink}Whatever, I don't care...{/pen}{space=200}"
    new "{pen=pink}随便，我不在乎……{/pen}{space=200}"
    old "Fool around with [saga.cast.tony] in his apartment."
    new "在他的公寓与[saga.cast.tony]亲热。"
    old "Have sex with [saga.cast.barb] in her office again."
    new "再次在她的办公室与[saga.cast.barb]做爱。"
    old "Have sex with [saga.cast.tori] in her office again."
    new "再次在她的办公室与[saga.cast.tori]做爱。"
    old "Wait for [saga.cast.jenny] to visit at night again."
    new "等[saga.cast.jenny]晚上再次来访。"
    old "{pen=blue}{size=+5}Anyway..{/size}{/pen}{space=180}"
    new "{pen=blue}{size=+5}总之..{/size}{/pen}{space=180}"
    old "{pen=pink}{size=+10}URGH!!!{/size}{/pen}{space=100}"
    new "{pen=pink}{size=+10}呃！！！{/size}{/pen}{space=100}"
    old "Accept [saga.cast.judith]'s offer in the bathroom."
    new "在浴室接受[saga.cast.judith]的提议。"
    old "Fool around with [saga.cast.jenny] in her bedroom."
    new "在她的卧室与[saga.cast.jenny]亲热。"
    old "Have sex with [saga.cast.viv] in her office again."
    new "再次在[saga.cast.viv]的办公室里和她做爱。"
    old "Put on another sex camshow with [saga.cast.jenny]."
    new "和[saga.cast.jenny]再开一场性爱直播。"
    old "We can't find my dad, can you come help us please?"
    new "我们找不到我爸爸，你能来帮帮我们吗？"
    old "{pen=orange}It got me thinking...{/pen}{space=250}"
    new "{pen=orange}这让我开始思考……{/pen}{space=250}"
    old "Have sex with [saga.cast.debbie] in the bathroom."
    new "在卫生间和[saga.cast.debbie]做爱。"
    old "Give [saga.cast.debbie] a rimjob in the shower."
    new "在淋浴间给[saga.cast.debbie]舔肛。"
    old "Have sex in the shower with [saga.cast.debbie]."
    new "和[saga.cast.debbie]在淋浴间做爱。"
    old "Peek at [saga.cast.debbie] when visiting Cupid."
    new "拜访丘比特时偷看[saga.cast.debbie]。"
    old "Progress through the [saga.cast.maria]'s story."
    new "推进[saga.cast.maria]的剧情。"
    old "The babies are coming! Meet me at the hospital!"
    new "宝宝们要出生了！快来医院见我！"
    old "Go down on [saga.cast.debbie] in the bathroom."
    new "在卫生间里帮[saga.cast.debbie]口交。"
    old "I'm in the washroom if you want to meet me..."
    new "我在洗手间，如果你想来找我……"
    old "Find [saga.cast.ariane] in a changing stall."
    new "在更衣隔间找到[saga.cast.ariane]。"
    old "Find [saga.cast.indira] in a changing stall."
    new "在更衣隔间找到[saga.cast.indira]。"
    old "Find [saga.cast.olivia] in a changing stall."
    new "在更衣隔间找到[saga.cast.olivia]。"
    old "First time with [saga.cast.tony]'s blessing."
    new "首次得到[saga.cast.tony]的祝福"
    old "I am Nigeria Prince, in needs of assistance!"
    new "我是尼日利亚王子，需要你的帮助！"
    old "Progress through [saga.cast.debbie]'s story."
    new "推进[saga.cast.debbie]的剧情。"
    old "Progress through [saga.cast.judith]'s story."
    new "推进[saga.cast.judith]的剧情。"
    old "Progress through [saga.cast.melody]'s story."
    new "推进[saga.cast.melody]的剧情。"
    old "The baby is coming! Meet me at the hospital!"
    new "宝宝要出生了！来医院找我！"
    old "Use the telescope to peek into Tammy's yard."
    new "用望远镜偷窥Tammy的院子。"
    old "Find [saga.cast.sammy] in a changing stall."
    new "在更衣隔间找到[saga.cast.sammy]。"
    old "Progress through [saga.cast.diane]'s story."
    new "推进[saga.cast.diane]的剧情。"
    old "Progress through [saga.cast.jenny]'s story."
    new "推进[saga.cast.jenny]的剧情。"
    old "Find [saga.cast.emma] in a changing stall."
    new "在更衣隔间找到[saga.cast.emma]。"
    old "Pablo69 wants to share a picture with you!"
    new "Pablo69想与你分享一张图片！"
    old "Progress through [saga.cast.barb]'s story."
    new "推进[saga.cast.barb]的剧情。"
    old "Progress through [saga.cast.tina]'s story."
    new "推进[saga.cast.tina]的剧情。"
    old "Progress through [saga.cast.tori]'s story."
    new "推进[saga.cast.tori]的剧情。"
    old "Find [saga.cast.sue] in a changing stall."
    new "在更衣隔间找到[saga.cast.sue]。"
    old "Progress through [saga.cast.viv]'s story."
    new "推进[saga.cast.viv]的剧情。"
    old "missing arguments: {must - kwargs.keys()}"
    new "缺少参数：{must - kwargs.keys()}"
    old "the {b}{size=-2}UNWANTED{/size}{/b} items"
    new "这些 {b}{size=-2}不需要的{/size}{/b} 物品"
    old "{pen=purple}For real!!{/pen}{space=250}"
    new "{pen=purple}真的！！{/pen}{space=250}"
    old "New toy is ULTRA strong! {emoji=heart}"
    new "新玩具超强！{emoji=heart}"
    old "[saga.cast.anon] is {sub=submissive}."
    new "[saga.cast.anon]处于{sub=顺从}状态。"
    old "[saga.cast.grace] again. Can we talk?"
    new "[saga.cast.grace]又来了。我们能谈谈吗？"
    old "FIRST TIME with my new ElectroClit!!"
    new "第一次用我的新电击阴蒂棒！！"
    old "Go shopping with [saga.cast.debbie]."
    new "和[saga.cast.debbie]一起去购物。"
    old "[saga.cast.anon] is {dom=assertive}."
    new "[saga.cast.anon]处于{dom=强势}状态。"
    old "Fantasizing about [saga.cast.anon]."
    new "幻想和[saga.cast.anon]"
    old "[what!i] is now available to visit."
    new "[what!i]现在可以拜访了。"
    old "Fantasizing about a sugar daddy."
    new "幻想和一位金主爸爸"
    old "New cookie jar variant unlocked!"
    new "新角色图鉴变体解锁！"
    old "Progress through the main story."
    new "推进主线剧情。"
    old "Your item(s) have been shipped!"
    new "你的物品已发货！"
    old "New cookie jar scene unlocked!"
    new "新角色图鉴场景解锁！"
    old "Narrative, second trimester."
    new "叙事，孕中期。"
    old "OMG!! I'm soooo FULL!!! ¦D~~"
    new "天呐！！我吃得好饱！！！¦D~~"
    old "Your earnings for this month"
    new "您本月的收入"
    old "Migrated from [ver] to [cv]"
    new "从[ver]迁移至[cv]"
    old "Narrative, third trimester."
    new "叙事，孕晚期。"
    old "{color=1ceda7}TODO:{/color}"
    new "{color=1ceda7}待办事项：{/color}"
    old "Thank you for subscribing!"
    new "感谢您的订阅！"
    old "Baby come. I go hospital."
    new "宝宝要出生了。我得去医院。"
    old "Half wind-relieving pose."
    new "半排气式"
    old "Progress through day one."
    new "度过第一天"
    old "Repeat, second trimester."
    new "重复，孕中期。"
    old "Suggest a threeway again."
    new "再次提议三人行"
    old "[what!i] added to basket."
    new "[what!i]已添加到购物车"
    old "Repeat, third trimester."
    new "重复，孕晚期。"
    old "After pregnant camshow."
    new "怀孕直播后。"
    old "Confident (first-time)."
    new "自信(首次)"
    old "Playing with her teddy."
    new "正在玩她的泰迪熊"
    old "Proactive (first-time)."
    new "主动(初次)"
    old "EMPLOYEE OF THE MONTH"
    new "月度最佳员工"
    old "He loves bug reports!"
    new "他最喜欢收bug报告了！"
    old "Tempted (first-time)."
    new "受诱惑(初次)"
    old "Threeway, confident."
    new "三人行，自信"
    old "Threeway, tentative."
    new "三人行，犹豫"
    old "Dolphin plank pose."
    new "海豚式平板支撑。"
    old "Leisure Suit Harold"
    new "休闲西装Harold"
    old "Dusk (first-time)."
    new "黄昏(首次)"
    old "My favorite toy ;)"
    new "我最喜欢的玩具 ;)"
    old "Noon (first-time)."
    new "中午(首次)"
    old "chocolate frosting"
    new "巧克力糖霜"
    old "Second trimester."
    new "孕中期"
    old "Shy (first-time)."
    new "害羞(首次)"
    old "stop things there"
    new "到此为止"
    old "Catalogue locked"
    new "目录已锁定"
    old "Getting dressed."
    new "正在穿衣"
    old "Third trimester."
    new "孕晚期"
    old "couldn't help it"
    new "忍不住"
    old "stop things here"
    new "到此为止"
    old "strawberry glaze"
    new "草莓糖霜"
    old "vanilla frosting"
    new "香草糖霜"
    old "xX~HOTKITTY69~Xx"
    new "xX~热辣小猫69~Xx"
    old "Outlood Express"
    new "Outlood快递"
    old "Repeat, denial."
    new "再次，拒绝。"
    old "Summertime SAGA"
    new "夏日传奇"
    old "Waning Crescent"
    new "残月"
    old "Waxing Crescent"
    new "娥眉月"
    old "Waxing Gibibous"
    new "盈凸月"
    old "blueberry glaze"
    new "蓝莓釉"
    old "chocolate chips"
    new "巧克力碎"
    old "vanilla drizzle"
    new "香草淋酱"
    old "Triangle pose."
    new "三角式"
    old "Waning Gibbous"
    new "亏凸月"
    old "freq next prev"
    new "频率 下一个 上一个"
    old "{}:{}: missing"
    new "{}:{}: 缺失"
    old "First Quarter"
    new "上弦月"
    old "Masturbation."
    new "自慰"
    old "My room, NOW!"
    new "来我的房间，立刻！"
    old "Not pregnant."
    new "未怀孕"
    old "Remote Access"
    new "远程访问"
    old "Third Quarter"
    new "下弦月"
    old "maple drizzle"
    new "枫糖淋酱"
    old "GAME OVER..."
    new "游戏结束……"
    old "Never-Life 3"
    new "绝命3"
    old "Unimpressed."
    new "不感兴趣"
    old "push further"
    new "更进一步"
    old "Drying off."
    new "擦干"
    old "First time."
    new "初次"
    old "Invitation."
    new "邀请"
    old "Lemon twist"
    new "柠檬扭纹"
    old "Maze Runner"
    new "移动迷宫"
    old "Miss DeWitt"
    new "德威特小姐"
    old "Miss Dewitt"
    new "德威特小姐"
    old "Raven Hill."
    new "渡鸦山"
    old "Recycle Bin"
    new "回收站"
    old "angle speed"
    new "角速度"
    old "locker room"
    new "更衣室"
    old "piña colada"
    new "piña colada（椰林飘香）"
    old "reach lower"
    new "向下伸展"
    old "Narrative."
    new "叙事"
    old "New Folder"
    new "新建文件夹"
    old "Pot of cum"
    new "一罐精液"
    old "Proactive."
    new "主动"
    old "Ucumtu-r34"
    new "Ucumtu-r34"
    old "don't stop"
    new "别停下"
    old "keep going"
    new "继续"
    old "kiss lower"
    new "再往下吻"
    old "send nudes"
    new "发裸照"
    old "Basement."
    new "地下室"
    old "Doubtful."
    new "将信将疑"
    old "Failout 3"
    new "败退3"
    old "Resigned."
    new "无奈"
    old "Rodríguez"
    new "罗德里格斯"
    old "Wish List"
    new "愿望单"
    old "data font"
    new "数据字体"
    old "right now"
    new "立刻"
    old "Annoyed."
    new "恼怒"
    old "Ice cube"
    new "冰块"
    old "Kitchen."
    new "厨房"
    old "Nervous."
    new "紧张"
    old "Tempted."
    new "受诱惑"
    old "not ugly"
    new "不丑"
    old "Garage."
    new "车库"
    old "LOL!! 🤣"
    new "LOL！！🤣"
    old "Office."
    new "办公室"
    old "Repeat."
    new "再次"
    old "Yoo-suk"
    new "Yoo-suk"
    old "acc pin"
    new "账户PIN"
    old "not you"
    new "不是你"
    old "tv auth"
    new "电视授权"
    old "tv auto"
    new "电视自动"
    old "tv info"
    new "电视信息"
    old "Shower"
    new "淋浴"
    old "First."
    new "首次"
    old "Krüger"
    new "克鲁格"
    old "Dusk."
    new "黄昏"
    old "HELP!"
    new "救命！"
    old "Noon."
    new "中午"
    old "Wash."
    new "洗澡"
    old "Yoga."
    new "瑜伽"
    old "Gym."
    new "体育馆。"
    old "Shy."
    new "害羞"
